Make ScriptInterface more expressive and less repetitive
espressomd/espresso pull request #1079
Opened 2017-04-06 16:05 UTC by fweik

Fixes: Lack of magic
Description of changes:
 - More magic

This change adds a more convenient way of binding parameters in the script interface.
If you have a class
```c++
struct A {
  int i;
};
```
the SI can be implementet by deriving from AutoParameters and just listing which name
should be bound to what in the constructor, e.g.

```c++
 struct A : public AutoParameters {
   A() : AutoParameters({"expressive_name", i});
};
```
For more complicated cases, getters and setters can be provided as functions.

PR Checklist
------------
 - [x] Tests?
   - [x] Core

2017-04-07 07:43 UTC, hmenke approved these changes

2017-04-07 07:43 UTC, hmenke commented on src/core/utils/type_traits.hpp
> +struct is_instance_of<Template<T...>, Template> : public std::true_type {};
This only works for templates with `typename` parameters.  Perhaps a more expressive name is required.  Compile with `c++ -std=c++11 -c`

````cpp
#include <array>
#include <type_traits>

template <typename T, template <typename...> class Template>
struct is_instance_of : public std::false_type {};

template <typename... T, template <typename...> class Template>
struct is_instance_of<Template<T...>, Template> : public std::true_type {};

bool fail = is_instance_of< std::array<int,2> , std::array<int,2> >::value;
````

2017-04-07 07:43 UTC, hmenke commented on src/script_interface/Variant.hpp
> +};
This substitution allows down-conversion from `int` to `short` or even `char`.  I wouldn't make the assumption what people only pass sufficiently short values through this.

2017-04-07 07:43 UTC, hmenke commented on src/script_interface/Variant.hpp
> +};
This substitution allows up-coversion to `long double` which results in a bogus digits in the extra decimal places.  #1051 is a good example for this.

2017-04-07 07:43 UTC, hmenke commented on src/script_interface/h5md/h5md.hpp
> +#include "auto_parameters/AutoParameters.hpp"
Perhaps add `auto_parameters/` to the search path?  This here is not so nice.

2017-04-07 08:48 UTC, fweik commented on src/script_interface/Variant.hpp
> +};
You are right, I'm not sure what the right way to deal with this is. We could either only allow stuff that is large enough (excluding everything smaller than 32 bit), or do a runtime check. What do you think?

2017-04-07 08:49 UTC, fweik commented on src/script_interface/Variant.hpp
> +};
The "bogus digits" are only a problem when comparisons are not done in a proper way. But this also allows for narrowing, which could be a problem. Runtime checks are not so easy for floats. So only allow float & double?

2017-04-07 09:00 UTC, hmenke commented on src/script_interface/Variant.hpp
> +};
I would only offer specializations for types which are actually Variant members.  For everything else the conversion behaviour is too ambiguous and might lead to unexpected results (narrowing, precision loss, etc.).

I think it is reasonable to demand that classes compatible with ScriptInterface should use compatible types, i.e. those in Variant.  If clients are keen on messing with the types they can still do this with an explicit cast/conversion.
````cpp
struct infer_type_helper<
    T, typename std::enable_if<std::is_same<T,int>::value, void>::type> {
  static constexpr VariantType value{VariantType::INT};
};

struct infer_type_helper<
    T, typename std::enable_if<std::is_same<T,double>::value, void>::type> {
  static constexpr VariantType value{VariantType::DOUBLE};
};
````

2017-04-07 09:05 UTC, fweik commented
Sounds reasonable.

On Fri, Apr 7, 2017 at 11:00 AM Henri Menke <notifications@github.com>
wrote:

> *@hmenke* commented on this pull request.
> ------------------------------
>
> In src/script_interface/Variant.hpp
> <https://github.com/espressomd/espresso/pull/1079#discussion_r110345941>:
>
> > +namespace detail {
> +template <typename T, typename = void> struct infer_type_helper {};
> +
> +template <> struct infer_type_helper<bool> {
> +  static constexpr VariantType value{VariantType::BOOL};
> +};
> +
> +template <> struct infer_type_helper<std::string> {
> +  static constexpr VariantType value{VariantType::STRING};
> +};
> +
> +template <typename T>
> +struct infer_type_helper<
> +    T, typename std::enable_if<std::is_integral<T>::value, void>::type> {
> +  static constexpr VariantType value{VariantType::INT};
> +};
>
> I would only offer specializations for types which are actually Variant
> members. For everything else the conversion behaviour is too ambiguous and
> might lead to unexpected results (narrowing, precision loss, etc.).
>
> I think it is reasonable to demand that classes compatible with
> ScriptInterface should use compatible types, i.e. those in Variant. If
> clients are keen on messing with the types they can still do this with an
> explicit cast/conversion.
>
> struct infer_type_helper<
>     T, typename std::enable_if<std::is_same<T,int>::value, void>::type> {
>   static constexpr VariantType value{VariantType::INT};
> };
> struct infer_type_helper<
>     T, typename std::enable_if<std::is_same<T,double>::value, void>::type> {
>   static constexpr VariantType value{VariantType::DOUBLE};
> };
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/pull/1079#discussion_r110345941>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA2i3wEZtNu2Ja5iNfo33oLxPlTIEMT6ks5rtfslgaJpZM4M10XE>
> .
>

2017-04-07 09:49 UTC, fweik commented on src/core/utils/type_traits.hpp
> +struct is_instance_of<Template<T...>, Template> : public std::true_type {};
Suggestions?

2017-04-07 13:21 UTC, RudolfWeeber commented
Conentwise this is very nice. 
But since there is a lot of hard to read template magic, please put more comments in the code, which explain what stuff is doing.

2017-04-10 23:32 UTC, hmenke requested changes

2017-04-10 23:32 UTC, hmenke commented on src/core/unit_tests/Variant_test.cpp
> +  transform_vectors(v)
Semicolon missing.

2017-04-11 08:11 UTC, fweik commented
@RudolfWeeber

2017-04-16 00:24 UTC, hmenke approved these changes

2017-04-18 08:39 UTC, merged