Lb testcases
espressomd/espresso pull request #1159
Opened 2017-05-08 15:45 UTC by KunTares

Added testcases lb.py, lb_gpu.py and lb_stokes_sphere.py.
Partial fix for lbboundaries force interface.

2017-05-18 13:18 UTC, rempferg commented
The test case lb.py requires a file lb_system.data, which seems to be missing.

2017-05-18 14:03 UTC, rempferg requested changes
- I added all existing test cases to make check and corrected that one erroneous comma
- I removed erroneous integrate.integrate(100) lines from lb_test*.py
- I added all existing test cases to make check and corrected that one erroneous comma
- added ut decorators to only run minimize_energy test if LJ is compiled in

TODO
- add lb_system.data
- lb_test*.py do not contain asserts
- add decorators to only run LB tests of respective LB features compiled in

2017-05-18 14:03 UTC, rempferg commented on testsuite/python/lb.py
> +		data = np.genfromtxt("lb_system.data")
Please add this file.

2017-05-22 21:26 UTC, hmenke requested changes

2017-05-22 21:26 UTC, hmenke commented on testsuite/python/lb.py
> +@ut.skipIf('LB' not in espressomd.code_info.features(),
Please use `has_features`.  The `code_info` is not a user module.
````python
@ut.skipIf(not espressomd.has_features(["LB"]),
           "Features not available, skipping test!")
````

2017-05-22 21:26 UTC, hmenke commented on testsuite/python/lb_gpu.py
> +@ut.skipIf('LB_GPU' not in espressomd.code_info.features(),
Please use `has_features`.  The `code_info` is not a user module.
````python
@ut.skipIf(not espressomd.has_features(["LB_GPU"]),
           "Features not available, skipping test!")
````

2017-05-22 21:26 UTC, hmenke commented on testsuite/python/lb.py
>  			q = particle[2]
`q` is now unused.  Please remove.

2017-05-22 21:26 UTC, hmenke commented on testsuite/python/lb_gpu.py
>  			q = particle[2]
`q` is now unused. Please remove.

2017-05-26 11:26 UTC, hmenke approved these changes

2017-06-23 09:31 UTC, rempferg approved these changes

2017-06-28 13:56 UTC, rempferg commented
I don't understand how the particle temperature can be 2 here. The calculation seems correct to me. Also, I can't reproduce this locally.

2017-09-18 17:06 UTC, fweik commented
@rempferg @KunTares please check again. If fixed the two thermostat tests, and add the gpu stokes sphere test, which seemed ok.

2017-09-19 15:07 UTC, rempferg commented
Looks good to me. Unfortunately I don't see a way to make the calculation of the fluid statistics faster without significant work.

2017-09-19 15:07 UTC, rempferg approved these changes

2017-09-19 15:08 UTC, merged