Dynamic properties for ParticleSlice
espressomd/espresso pull request #1160
Opened 2017-05-08 15:48 UTC by mkuron

Fixes #958.

@RudolfWeeber @fweik @hmenke

Any properties that are not defined for `ParticleSlice` are automatically drawn from `ParticleHandle`, including docstrings. To the setter, one can either provide one value that is set on all particles or a list of values where the order corresponds to that of the slice members.

This turned out to be surprisingly difficult:
- One cannot use `setattr` to add stuff to Cython classes, so I ended up wrapping the Cython class into a Python class that has all the autogenerated properties.
- The wrapping cannot be done in the loop I added to the end of particle_data.pyx. I had to introduce a class that holds the attribute name as a member. Otherwise the attribute name a setter/getter was operating on would vary in a non-deterministic fashion (seems like some kind of reference counting bug in Python itself...).

Further improvements made along the way:
 - Fix `ParticleSlice.__str__`, which previously didn't return anything as `int` is not the same as `numpy.int64`.
-  Improve `ParticleSlice.__str__` and `ParticleList.__str__` so that the representations look like Numpy arrays or Python lists. Previously there were newlines and the name was missing.
- Improve `utils.check_type_or_throw_except` so that it also allows `numpy.int64` where `int` is requested.

PR Checklist
------------
 - [x] Tests?
   - [x] Interface
   - [x] Core

2017-05-09 09:14 UTC, fweik approved these changes

2017-05-09 09:18 UTC, KaiSzuttor requested changes
Maybe add some more in-code documentation for future developers.

2017-05-09 09:29 UTC, mkuron commented
@KaiSzuttor, I'm currently refactoring `_InjectParticleProperty` to make it easier to understand. That should address your documentation request.

2017-05-09 10:22 UTC, hmenke commented on src/python/espressomd/particle_data.pyx
> +        return "ParticleSlice([" + res[:-2] + "])"
No need for this awkward comma removal
````python
pl = ParticleList()
return "ParticleSlice([" + ", ".join(str(pl[i]) for i in self.id_selection if pl.exists(i)) + "])"
````

2017-05-09 10:22 UTC, hmenke commented on src/python/espressomd/particle_data.pyx
> +        return "ParticleList([" + res[:-2] + "])"
No need for this awkward comma removal
````python
return "ParticleList([" + ", ".join(str(self[i]) for i in range(max_seen_particle + 1) if self.exists(i)) + "])"
````

2017-05-09 11:38 UTC, mkuron commented on src/python/espressomd/particle_data.pyx
> +        return "ParticleSlice([" + res[:-2] + "])"
It's nicer, and it's more in line with how Python and Numpy print their own data types. Also, if I remove that space at the end, why not remove the trailing comma along with it.

2017-05-09 12:42 UTC, mkuron commented
I was able to get rid of the injector class by switching to `functools.partial`. It seems like the following two are different here, even though they look like they do the same:
```
functools.partial(geta, attribute=attribute_name)
lambda s: geta(s, attribute_name)
```
Explicitly capturing the loop variable like this
```
def geta(particle_slice, attribute=attribute_name):
```
didn't help either, even though that is the standard solution for this problem in pure Python. I really don't understand what is going on here, might be a Cython bug.

Anyway, once Travis passes, I think this can be merged.

2017-05-09 21:50 UTC, hmenke approved these changes

2017-05-11 08:37 UTC, mkuron commented
Small change to the getter so it writes straight to a numpy array instead of converting a list into one at the end. Also extend unit test so it covers all code paths.

2017-05-11 10:15 UTC, hmenke approved these changes

2017-05-11 13:32 UTC, merged