Cuda Python Interface (Listing/Selecting devices) + Docs
espressomd/espresso pull request #1161
Opened 2017-05-08 15:58 UTC by etzaras

Fixes #946, #1112 

Description of changes:
 - Implemented device listing in python interface
 - Documented usage of GPU selection

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [x] Docs?

I'm not entirely sure if I described the usage correctly.
Someone knowledgeable should provide input in that case :)

2017-05-08 22:03 UTC, hmenke approved these changes

2017-05-15 12:27 UTC, mkuron requested changes

2017-05-15 12:27 UTC, mkuron commented on doc/sphinx/cuda.rst
> +be selected. If you wanted
Duplicated _If you wanted_.

2017-05-15 12:27 UTC, mkuron commented on doc/sphinx/cuda.rst
> +your GPU should at least have compute capability 2.0.
_needs to have_

And mention that it needs to be an Nvidia GPU.

2017-05-16 08:11 UTC, mkuron approved these changes

2017-05-16 09:46 UTC, merged