Work on the developers guide
espressomd/espresso pull request #1168
Opened 2017-05-09 13:07 UTC by RudolfWeeber

This improves the sphinx version of the developrs guide.
New stuff on contacting developers, starting new development projects, cmake build system, doc structure, testsuite structure
Up-to-date version of adding bonded ia
Up-to-date version of global variables
Outdated infromation has been marked as such or removed entirely, depending on re-usability.

This pr also removes the LaTex version, which should no longer be used or changed.

There is much more to do at future coding days.

2017-05-09 14:43 UTC, KaiSzuttor requested changes

2017-05-09 14:43 UTC, KaiSzuttor commented on doc/sphinx/dg.rst
> +.. _contact:
Please use labels that match exactly the heading (except for the leading underscore).

2017-05-09 14:43 UTC, KaiSzuttor commented on doc/sphinx/dg.rst
>  .. _development_environment:
Same here, please correct the label.

2017-05-09 14:43 UTC, KaiSzuttor commented on doc/sphinx/dg.rst
> +-  The documentation is currently being converted form Latex to Sphinx. To build the old user and developer guides, you will need LaTex. For building tthe sphinx documentation, you will need the Pyth
typo "from"

2017-05-09 14:43 UTC, KaiSzuttor commented on doc/sphinx/dg.rst
> +.. _getting_the_development_code:
Same here, please correct label.

2017-05-09 14:43 UTC, KaiSzuttor commented on doc/sphinx/dg.rst
> +* In some cases (e.g., src/core/CMakeList.txt), the CMakeList.txt contains a wild-card include like this
Maybe we should mention that wildcards are in general a bad idea in CMakeLists.txt files.

2017-05-09 14:43 UTC, KaiSzuttor commented on doc/sphinx/dg.rst
> +-  In-code documentation for the Python interface is located in the various files in src/python/espressomd and also makes use of the Sphinx Python package
Mentioning the numpydoc package and the respective doc style.

2017-05-09 14:43 UTC, KaiSzuttor commented on doc/sphinx/dg.rst
> +* Simulatino core:
typo "Simulation"

2017-05-09 14:59 UTC, fweik commented on doc/sphinx/dg.rst
> +* In some cases (e.g., src/core/CMakeList.txt), the CMakeList.txt contains a wild-card include like this
I am not convinced that this is true.

2017-05-09 15:22 UTC, RudolfWeeber commented
On Tue, May 09, 2017 at 07:59:42AM -0700, Florian Weik wrote:
> +To add new files to |es| (like C++ source files or header files) you
> +need to look at the CMakeList.txt in the directory where the file is located.
> +* Please note that .hpp-header files usually do not have to be added to CMakeList.txt
> +* In some cases (e.g., src/core/CMakeList.txt), the CMakeList.txt contains a wild-card include like this
> 
> I am not convinced that this is true.
Which statement exactly?
Concerning the wild cards: I'm quoting the part of the CMakeList
Concerning headers: apart from special cases like the feature
handling, they aren't for src/core and src/script_interface

2017-05-09 15:27 UTC, fweik commented
No, the statement by @KaiSzuttor that wildcards are a bad idea.

2017-05-09 22:28 UTC, jonaslandsgesell commented
Kai is probably refering to the need to rerun cmake when adding a new source file if the CMakeList is not modified. https://cmake.org/pipermail/cmake/2007-February/012833.html

2017-05-10 12:48 UTC, fweik approved these changes
Excellent

2017-05-10 13:36 UTC, KaiSzuttor commented on doc/sphinx/dg.rst
> +.. _Contact the Develoeprs:
You totally followed my remarks but I didn't meant to copy typos 😃

2017-05-10 21:49 UTC, hmenke requested changes

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +   outdated.  Please see the section :ref:contact` and
`` :ref:`contact` `` has been renamed to `` :ref:`Contact_the_Developers` ``

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +,, _Required Development Tools:
`.. _Required Development Tools:` (two dots, not two commas)

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +-  First of all, please install the dependencies for compiling |es|. See :ref:`_Getting, comping and running`
There is no label `` :ref:`_Getting, comping and running` ``

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +-  The documentation is currently being converted from Latex to Sphinx. To build the old user and developer guides, you will need LaTex. For building tthe sphinx documentation, you will need the Pyth
Latex, LaTex?  It should be LaTeX.  Also: <strike>tthe</strike> the

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +To contact the |es| developers, please write an email to the developerss mailing list:
<strike>developerss</strike> developers

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +   Note, that some distributions nonw use ``pip`` for Python3 and ``pip2`` for Python 2.
<strike>nonw</strike> now

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +-  To build the tutorials, you wil need LaTex.
<strike>wil</strike> will.  LaTex should be LaTeX.

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +-  The CMakeList.txt files in the ``src/``, ``doc/``, and ``testsuite/`` directories and their sub-directories
<strike>CMakeList.txt</strike> CMakeLists.txt

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +need to look at the CMakeList.txt in the directory where the file is located.
<strike>CMakeList.txt</strike> CMakeLists.txt

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +* Please note that .hpp-header files usually do not have to be added to CMakeList.txt
Remove "usually".  Header files *never* have to be added to CMakeLists.txt.  Only translation units have to be added.

2017-05-10 21:49 UTC, hmenke commented on doc/sphinx/dg.rst
> +Features/Algorithms should instead be encapsulated in a class which is used by the script interface mechnaism.
<strike>mechnaism</strike> mechanism

2017-05-18 09:57 UTC, pkreissl commented on doc/sphinx/dg.rst
> +  * Add calls to the force and energy calculatino functions to the force calculation in the integration loop as well as to energy and pressure/stress tensor analysis
[...] energy calculati**on** functions [...]

2017-05-18 10:03 UTC, pkreissl commented on doc/sphinx/dg.rst
> +* Pressur, stress tensor and virial calculation: If your bonded interaction is a pair bond and does not modify the particles involved, add simuilar code as above to presure.hpp:calc_bonded_pair_force
Pressur**e** [...] sim<s>u</s>ilar [...]

2017-05-18 10:03 UTC, pkreissl commented on doc/sphinx/dg.rst
> +Pleas note that the following is Cython code (www.cython.org), rather than pure Python.
Pleas**e**

2017-05-22 21:27 UTC, hmenke approved these changes

2017-05-23 09:10 UTC, merged