Dipolar support for scafacos, various fixes
espressomd/espresso pull request #1187
Opened 2017-05-27 15:24 UTC by RudolfWeeber

This adds dipolar Support for scafacos to the Python interface. It also adds test cases comparing existing dipolar methods against scafacos 2pnfft (from scafacos'  dipoles brnach).

There are also a bunch of Scafacos related fixes + some doc adaptation.

2017-05-28 04:35 UTC, hmenke requested changes

2017-05-28 04:35 UTC, hmenke commented on doc/sphinx/inter.rst
> +    method_params={"ewald\_r\_cut":1.5, "tolerance\_field":1e-3})
The backslashes matter here and are printed as is.  They are a relic from the LaTeX docs and should be remove in favour of literal underscores.

2017-05-28 04:35 UTC, hmenke commented on testsuite/python/scafacos_dipoles_1d_2d.py
> +    if "SCAFACOS_DIPOLES" in espressomd.features():
Please use the `skipIf` decorator as in
````python
@ut.skipIf(not espressomd.has_features(["SCAFACOS_DIPOLES"]),
           "Features not available, skipping test!")
class Scafacos1d2d(ut.TestCase):
````
Saves you also one level of indentation inside the class.

2017-05-28 22:02 UTC, hmenke approved these changes

2017-05-29 06:47 UTC, KaiSzuttor commented on src/core/initialize.cpp
> +#include "scafacos.hpp"
duplicate include

2017-05-29 06:51 UTC, KaiSzuttor commented on src/python/espressomd/electrostatics.pyx
> +    from .scafacos import *
wildcard imports are evil

2017-05-29 06:51 UTC, KaiSzuttor commented on src/python/espressomd/magnetostatics.pyx
> +from .actors cimport *
wildcard imports are evil

2017-05-31 15:45 UTC, fweik commented on testsuite/python/coulomb_cloud_wall.py
> +                self.compare("p3m_gpu", energy=False)
This seems wrong to me

2017-05-31 21:37 UTC, hmenke commented on testsuite/python/coulomb_cloud_wall.py
> +                self.compare("p3m_gpu", energy=False)
The changed name only leads to a wrong log message.  However, I wonder why energy comparison was disabled.

2017-05-31 21:37 UTC, hmenke commented on testsuite/python/magnetostaticInteractions.py
> +import espressomd
Duplicate import.

2017-06-06 21:42 UTC, hmenke approved these changes

2017-06-08 11:39 UTC, merged