Remove explicit cells loop
espressomd/espresso pull request #1191
Opened 2017-06-01 15:16 UTC by fweik

Description of changes:
 -  Removed for(cells) for(particles) loops by for(local_cells.particle()) where
    this was possible.

The remaining occurrence are mostly related to pair iteration or in the cell systems.
These are in maggs, mmm2d, iccp3m, collision, reaction, force, pressure, energy
and the cell systems.

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2017-06-01 23:06 UTC, hmenke approved these changes
Can we maybe agree that in the future you run clang-format after review?  Otherwise the changeset is just so huge and most of it is only whitespace,obfuscating the actual changes.

2017-06-01 23:06 UTC, hmenke commented on src/core/forces.cpp
> +    init_local_particle_force(&p);
(Applies to many other instances of this pattern in the changeset)
````cpp
std::for_each(std::begin(local_cells.particles()),
              std::end(local_cells.particles()),
              [](Particle &p){ init_local_particle_force(&p); });
````
The advantage is that with C++17 you can add an execution policy to this, possibly performing the unary function out of order.

2017-06-01 23:06 UTC, hmenke commented on src/core/lees_edwards_domain_decomposition.cpp
> +  for (m = 0; m < local_cells.n; m++) {
Missed this one?

2017-06-01 23:10 UTC, hmenke requested changes

2017-06-01 23:10 UTC, hmenke commented on src/core/lb.cpp
> +                  p->f.f[0], p->f.f[1], p->f.f[2]);
Should be `p.p.identity` and `p.f.f[0]` since `p` is no longer pointer type.

2017-06-01 23:10 UTC, hmenke commented on src/core/lb.cpp
> +                  p->f.f[0], p->f.f[1], p->f.f[2]);
Should be `p.p.identity` and `p.f.f[0]` since `p` is no longer pointer type.

2017-06-05 10:39 UTC, fweik commented on src/core/forces.cpp
> +    init_local_particle_force(&p);
Yes, but this has requirements on the body that must be checked individually. So you can't make this parallel without touching it anyway.

2017-06-05 10:40 UTC, fweik commented on src/core/lees_edwards_domain_decomposition.cpp
> +  for (m = 0; m < local_cells.n; m++) {
Nope, not a loop over particles (only over the cells)

2017-06-15 02:37 UTC, hmenke approved these changes

2017-07-04 10:37 UTC, hmenke commented on src/core/virtual_sites_com.cpp
> +  get_mi_vector(dist, p1_com.r.p, p2_com.r.p);
Why did you remove the debugging snippet?

2017-07-04 13:01 UTC, fweik commented
Because the new code will throw and not return NULL.

On Jul 4, 2017 12:37 PM, "Henri Menke" <notifications@github.com> wrote:

> *@hmenke* commented on this pull request.
> ------------------------------
>
> In src/core/virtual_sites_com.cpp
> <https://github.com/espressomd/espresso/pull/1191#discussion_r125443032>:
>
> > -    return;
> -  }
> -  if (p2_com == NULL) {
> -    fprintf(
> -        stderr,
> -        "No com found in get_mol_dist_vector_from_molid_cfg for mol id=%i\n",
> -        mol_id2);
> -    dist[0] = dist[1] = dist[2] = 0.0;
> -    return;
> -  }
> -#endif
> -  get_mi_vector(dist, p1_com->r.p, p2_com->r.p);
> +  auto &p1_com = get_mol_com_particle_from_molid_cfg(mol_id1);
> +  auto &p2_com = get_mol_com_particle_from_molid_cfg(mol_id2);
> +
> +  get_mi_vector(dist, p1_com.r.p, p2_com.r.p);
>
> Why did you remove the debugging snippet?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/pull/1191#pullrequestreview-47831768>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA2i3wzNW2EjEve-O7sUc1mRaaDzXNFFks5sKhXSgaJpZM4NtIfr>
> .
>

2017-08-10 21:17 UTC, hmenke approved these changes

2017-08-22 18:15 UTC, RudolfWeeber commented
I went through the changes.
Due to the size of changes and the un-obvious nature of teh diff, it is sometimes hard to ensure that things are doing the same as before. In particular for algorithms such as Maggs, Ghmc and the dipolar stuff.
In the end, one can only make sure with integration tests.
The question is, should we merge this independently of the short range pr, or do we do that in one go, as the short range pr has a lot of extra testing?
Weh reviewing the short range pr, can we take this one as basis for the comparrison?

2017-08-23 10:01 UTC, fweik commented
Sorry for the messy pull request. Maybe when we have a freeze for the release we can also run clang-format over the whole repo to avoid this kind of problems in the future.
The short range stuff is mostly orthogonal, as the short range calculations are always related to cells, and not to all particles. I don't think it has any additional tests in it that would help, and would merge it independently.  
Unfortunately I can not easily add tests for MEMD and GHMC because they are not accessible from python, the magnetostatics has tests iirc.

2017-08-23 10:42 UTC, RudolfWeeber commented
To me, it is clear that this needs to be merged, eventually. By
getting rid of the c-style array access and the repetetive loop
code, everything gets much more safe. 
Since two people have looked through it already, I think, we better
merge now, so if there are regressions, we have a good chance of
finding them before the school.

2017-09-05 07:55 UTC, merged