sphinx: fixing issue of cython functions not being recognized as pyth…
espressomd/espresso pull request #1431
Opened 2017-09-21 15:01 UTC by KaiSzuttor

…on code, thermostat decorator fix

2017-09-21 15:12 UTC, fweik commented
We could remove the python modules from the docker containers and run pip install requirements.txt to check that they are complete and sufficient to build. (decorator module is missing in docker)

2017-09-21 15:36 UTC, mkuron commented
@fweik, then we'd give up testing whether Espresso runs with the distribution (older) package versions. Since our requirements are rather trivial, we shouldn't require everyone to use requirements.txt.

2017-09-21 15:42 UTC, mkuron commented
@KaiSzuttor, `decorator.decorator`'s job is pretty trivial. We shouldn't need to add a module and intoduce a dependency just to do that, you can probably do it in five lines yourself.

2017-09-21 21:26 UTC, hmenke approved these changes

2017-09-22 12:08 UTC, mkuron requested changes

2017-09-22 12:08 UTC, mkuron commented on src/python/espressomd/thermostat.pyx
> +from decorator import decorator
`decorator.decorator`'s job is pretty trivial. We shouldn't need to add a module and intoduce a dependency just to do that, you can probably do it in five lines yourself. [`decorator`](https://github.com/micheles/decorator/blob/master/src/decorator.py) uses `exec` inside, so it's a pretty terrible hack anyway!

2017-09-25 15:24 UTC, fweik approved these changes

2017-09-25 21:26 UTC, hmenke approved these changes

2017-09-25 21:26 UTC, hmenke commented on src/python/espressomd/thermostat.pyx
> +    def decoratorfunction(function):
Perhaps you could have *not* removed the docstring.

2017-09-25 21:27 UTC, hmenke commented on src/python/espressomd/thermostat.pyx
> +    def decoratorfunction(function):
Sorry, GitHub showed me an outdated file.

2017-09-26 06:50 UTC, mkuron approved these changes
Does this also work in Python 2.7? I think `functools.wraps` didn't treat docstrings until Python ~3.5.

2017-09-26 07:32 UTC, KaiSzuttor commented
yes

2017-09-26 09:08 UTC, KaiSzuttor commented
done, can be merged

2017-09-29 20:07 UTC, merged