unit test for analyze_energy
espressomd/espresso pull request #1469
Opened 2017-10-04 10:19 UTC by davidsean

Fixes #1312

Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2017-10-04 12:35 UTC, KaiSzuttor requested changes

2017-10-04 12:35 UTC, KaiSzuttor commented on testsuite/analyze_energy.py
> +#from espressomd.interactions import *
Please remove

2017-10-04 12:35 UTC, KaiSzuttor commented on testsuite/analyze_energy.py
> +
Please remove empty line

2017-10-04 12:35 UTC, KaiSzuttor commented on testsuite/analyze_energy.py
> +        self.assertTrue( np.allclose(energy["total"], 25.))
Please run autopep8 -i on that file to get rid of the unnecessary blanks

2017-10-04 12:35 UTC, KaiSzuttor commented on testsuite/analyze_energy.py
> +class test_analyze_energy(ut.TestCase):
Recommended is camelcase namestyle for classes

2017-10-04 12:35 UTC, KaiSzuttor commented on testsuite/analyze_energy.py
> +
remove empty line

2017-10-04 12:35 UTC, KaiSzuttor commented on testsuite/analyze_energy.py
> +    #ut.main()
remove that line

2017-10-04 12:55 UTC, KaiSzuttor commented on testsuite/analyze_energy.py
> +    system.non_bonded_inter[0, 0].lennard_jones.set_params(
Move that part into the setUp method of unittest

2017-10-05 11:57 UTC, fweik approved these changes

2017-10-05 12:21 UTC, KaiSzuttor commented
test is failing...

2017-10-05 13:20 UTC, KaiSzuttor commented on testsuite/analyze_energy.py
> +        self.assertTrue(np.allclose(energy["total"], 1.))
That fails because you  still have particles from tests before.

2017-10-05 13:21 UTC, KaiSzuttor commented on testsuite/analyze_energy.py
> +        self.assertTrue(np.allclose(energy["kinetic"], 0.))
please use self.assertAlmostEqual(a, b, delta=1e-7) or similar

2017-10-05 16:24 UTC, KaiSzuttor approved these changes

2017-10-05 18:00 UTC, merged