Fixed bug in ELC
espressomd/espresso pull request #1580
Opened 2017-10-30 10:05 UTC by KonradBreitsprecher

Fixes ELC part of #1559 and probalby #229  

 - Found small but fatal bug in elc.cpp. Also I could no longer reproduce the error in ELCIC and it agrees with MMM2D with two particles and metallic plates.

2017-10-30 10:11 UTC, KaiSzuttor reviewed
please remove debug printfs

2017-10-30 23:58 UTC, fweik requested changes
Looks good to me, aside from the obvious stuff that needs to be changed.

2017-10-30 23:58 UTC, fweik commented on src/python/espressomd/particle_data.pyx
> +            ret = np.array([ppos[0], ppos[1], ppos[2]])
This should not be in here.

2017-10-30 23:58 UTC, fweik commented on src/core/elc.cpp
> +    printf("ELC_set_params tune\n");
Left over printf

2017-10-30 23:58 UTC, fweik commented on src/core/elc.cpp
> +  printf("far_cut %f\n far_cut2 %f\n h %f\n space_layer %f\n space_box %f\n far_calculated %d\n addmesh %f %f %f\n",elc_params.far_cut,elc_params.far_cut2, elc_params.h, elc_params.space_layer, elc_p
Left over printf

2017-10-30 23:58 UTC, fweik commented on src/core/elc.cpp
> +    printf("ELC_init tune\n");
Left over printf

2017-10-30 23:58 UTC, fweik commented on src/core/elc.cpp
> +  printf("ELC_init\n");
Left over printf

2017-10-30 23:58 UTC, fweik commented on src/core/elc.cpp
> +  printf("ELC_tune\n");
Left over printf

2017-11-02 14:36 UTC, fweik approved these changes

2017-11-03 14:15 UTC, fweik approved these changes

2017-11-03 14:16 UTC, merged