py: script interface variant conversion handles numpy's int and float iqypes
espressomd/espresso pull request #1595
Opened 2017-11-07 16:07 UTC by RudolfWeeber

Fixes #1174

2017-11-07 18:56 UTC, fweik approved these changes

2017-11-08 01:52 UTC, hmenke requested changes

2017-11-08 01:52 UTC, hmenke commented on src/python/espressomd/script_interface.pyx
> +        elif type(value) == int or isinstance(value,np.int):
Probably it should be
```python
elif np.issubdtype(np.dtype(type(value)), int):
```
This interactive session at least looks good (Output in Python 2 and 3 is the same).  It also solves the problem that `bool` is falsely recognized as `np.in`.
```python
>>> value = 2
>>> np.issubdtype(np.dtype(type(value)), int)
True
>>> value = np.int64(2)
>>> np.issubdtype(np.dtype(type(value)), int)
True
>>> value = 2.0
>>> np.issubdtype(np.dtype(type(value)), int)
False
>>> value = np.float64(2.0)
>>> np.issubdtype(np.dtype(type(value)), int)
False
>>> value = True
>>> np.issubdtype(np.dtype(type(value)), int)
False
>>> value = "Definitely not a number"
>>> np.issubdtype(np.dtype(type(value)), int)
False
```

2017-11-08 01:52 UTC, hmenke commented on src/python/espressomd/script_interface.pyx
> +        elif type(value) == float or isinstance(value,np.float):
See other comment.
```python
elif np.issubdtype(np.dtype(type(value)), float):
```

2017-11-08 18:27 UTC, hmenke approved these changes

2017-11-08 21:39 UTC, merged