Observable lb
espressomd/espresso pull request #1613
Opened 2017-11-13 15:45 UTC by KaiSzuttor

Description of changes:
 - contains #1594
 - adds an observable and test for the LB fluid velocity in polar coordinates at particle positions

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2017-11-15 15:14 UTC, fweik requested changes

2017-11-15 15:14 UTC, fweik commented on src/core/observables/CylindricalLBFluxDensityProfileAtParticlePositions.hpp
> +class CylindricalLBFluxDensityProfileAtParticlePositions : public CylindricalProfileObservable {
Please move the implementation to a .cpp file. Then you don't have to drag in the other headers here, which are not actually part of the interface. That also decreases the build time.

2017-11-15 15:14 UTC, fweik commented on src/core/utils/Histogram.hpp
> +#ifndef HISTOGRAM_HPP
Should correspond to the file path, e.g. CORE_UTILS_HISTOGRAM_HPP, so that there can not be collisions.

2017-11-29 07:41 UTC, KaiSzuttor commented
just found there is still sth wrong...

2017-11-29 11:06 UTC, KaiSzuttor commented
Ready for review @fweik

2017-12-06 21:26 UTC, fweik approved these changes

2017-12-06 21:26 UTC, merged