Added LjCos2 non-bonded interaction
espressomd/espresso pull request #1643
Opened 2017-11-23 00:18 UTC by NishchaySuri

Fixes #

Description of changes:
 - Changes are made in interactions.pyx and interactions.pxd
 - A class is added to include the lennard-jones cosine2 non-bonded interaction. It is placed in the LENNARD_JONES directive! (Was not sure if this is how you want it structured)
- I have compiled it and is working.

Please tell me if it is okay or if I need to make any changes? I would be glad to contribute
Thanks!
-Nishchay Suri

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2017-11-23 01:27 UTC, hmenke commented
Thank you very much for your contribution!  The code looks reasonable.  One of the tests failed because the `LJCOS2` feature is not always enabled, so I added some guards for you.  Please also adhere to the Python [PEP8](https://www.python.org/dev/peps/pep-0008/) naming convention.

Before this can be merged, you have to add a testcase though.

2017-12-01 00:54 UTC, NishchaySuri commented
I have added the testcase for Ljcos2 and a data file it pulls from named test_ljcos2.dat

2017-12-02 18:51 UTC, NishchaySuri commented
I have added the test case for lj-cos2 interaction. It is passing all the tests. Please see if this is all you wanted for the merge!

Happy to contribute!
Thank you
-Nishchay Suri

2017-12-05 11:26 UTC, pkreissl requested changes
The python interfaces for both interactions look good. However, I don't think that `offset` needs to be a required key.

Please autopep8 your python files (`autopep8 -i <filename>`).

Concerning the testcase:
Please add your test to the `testsuite/CMakeLists.txt`. Otherwise your test will not be run automatically.

If I am not mistaken, a testcase for the LJCOS interaction is still missing.

2017-12-05 11:26 UTC, pkreissl commented on doc/sphinx/inter.rst
> +(:math:`c_\mathrm{shift}=0`). Between and , a cosine is used to
Between ? and ?

2017-12-05 11:26 UTC, pkreissl commented on src/python/espressomd/interactions.pyx
> +            return "epsilon", "sigma", "cutoff", "offset"
Is `offset` really required (default is `offset=0`)?

2017-12-05 11:26 UTC, pkreissl commented on src/python/espressomd/interactions.pyx
> +            return "epsilon", "sigma", "offset", "width"
Again, is explicitly setting `offset` really necessary?

2017-12-05 11:26 UTC, pkreissl commented on src/python/espressomd/interactions.pyx
> +                "offset"  :ia_params.LJCOS_offset,
Please use autopep8 you python files.

2017-12-05 11:26 UTC, pkreissl commented on testsuite/test_ljcos2.py
> +# This is a unit-test for Lennard Jones Cosine2 non-bonded interaction
Please autopep8 this file!

2017-12-07 11:09 UTC, pkreissl commented on doc/sphinx/inter.rst
> +(:math:`c_\mathrm{shift}=0`). Between and , a cosine is used to
Between :math:`r_\mathrm{min}` and :math:`r_\mathrm{cut}`, ...
(see [ESPResSo User’s Guide](http://espressomd.org/wordpress/wp-content/uploads/2017/06/ESPResSo_3.3.1_UsersGuide.pdf), Section 5.1.4. Lennard-Jones cosine interaction)

2017-12-17 00:10 UTC, NishchaySuri commented
All files are autopep8'ed and I also added

2017-12-17 00:10 UTC, closed without merging