added coulomb contribution from P3M
espressomd/espresso pull request #1648
Opened 2017-11-23 20:18 UTC by davidsean

Fixes #

Description of changes:
 - added coulomb contribution with P3M

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2017-11-23 20:31 UTC, hmenke commented on testsuite/analyze_energy.py
> +@ut.skipIf(not espressomd.has_features("P3M"), "Skipped because LENNARD_JONES turned off.")
You could also do
```python
@ut.skipIf(not espressomd.has_features("LENNARD_JONES", "ELECTROSTATICS", "P3M"),
           "Missing features: " + ", ".join(espressomd.missing_features("LENNARD_JONES", "ELECTROSTATICS", "P3M")))
```
or with even less duplication
```python
features = ["LENNARD_JONES", "ELECTROSTATICS", "P3M"]
@ut.skipIf(not espressomd.has_features(*features),
           "Missing features: " + ", ".join(espressomd.missing_features(*features)))
```

2017-11-24 19:09 UTC, fweik requested changes

2017-11-24 19:09 UTC, fweik commented on testsuite/analyze_energy.py
> +        0.0
This looks wrong to me.

2017-11-24 19:09 UTC, fweik commented on testsuite/analyze_energy.py
> +        p3m = electrostatics.P3M(bjerrum_length=1.0, accuracy=1e-7)
Can you please fix some of the p3m parameters to appropriate values, so that the tuning is faster?

2017-11-24 19:09 UTC, fweik commented on testsuite/analyze_energy.py
> +features = ["LENNARD_JONES", "ELECTROSTATICS", "P3M"]
Please move the p3m initialization and import to the test_electrostatics function and set the feature check there, so the rest of the test can run w/o electrostatics.

2017-11-28 11:28 UTC, fweik approved these changes

2017-11-28 20:23 UTC, merged