detailed exclusion error messages
espressomd/espresso pull request #1652
Opened 2017-11-24 12:02 UTC by KonradBreitsprecher

Fixes #1214 

- Extended exclusion error message for adding/deleting non-valid ids
- delete_exclusion now accepts lists and single int

2017-11-24 19:05 UTC, fweik commented
Does the setting of bonds/exclusions from a list work too? Also this should be covered in the particle_slice test.

2017-11-24 19:21 UTC, KonradBreitsprecher commented
I will check..

2017-11-30 15:30 UTC, KonradBreitsprecher commented
Setting slices now works for bonds, exclusions and vs_relative.
- Extensive tests in particle_slice.py
- Brief docu in part.rst
Please review @KaiSzuttor .

2017-11-30 15:44 UTC, KaiSzuttor requested changes

2017-11-30 15:44 UTC, KaiSzuttor commented on src/python/espressomd/particle_data.pyx
> +                check_type_or_throw_except(
has to be given as

2017-11-30 15:44 UTC, KaiSzuttor commented on src/python/espressomd/particle_data.pyx
> +                "Bond partners {} includes the particle {} itself.".format(bond[1:], self.id))
include~~s~~

2017-11-30 15:44 UTC, KaiSzuttor commented on src/python/espressomd/particle_data.pyx
> +            for i in range(len(self.id_selection)):
```python
for i in self.id_selection:
    ParticleHandle(i).delete_exclusion(_partner)
```

2017-11-30 15:44 UTC, KaiSzuttor commented on src/python/espressomd/particle_data.pyx
>          for i in range(len(self.id_selection)):
```python
for i in self.id_selection:
    ...
```

2017-11-30 15:44 UTC, KaiSzuttor commented on src/python/espressomd/particle_data.pyx
>          for i in range(len(self.id_selection)):
```python
for i in...
```

2017-11-30 15:44 UTC, KaiSzuttor commented on src/python/espressomd/particle_data.pyx
> +
remote blank line

2017-11-30 15:44 UTC, KaiSzuttor commented on src/python/espressomd/particle_data.pyx
>          fname: :obj:`str`
fname_ : :obj:`str`
blank between parameter name and colon for all parameters

2017-11-30 15:44 UTC, KaiSzuttor commented on src/python/espressomd/particle_data.pyx
> +
remove one blank

2017-11-30 15:44 UTC, KaiSzuttor commented on src/python/espressomd/utils.pyx
> +
please shortly describe what the function does

2017-11-30 15:44 UTC, KaiSzuttor commented on testsuite/particle_slice.py
>      state = [[0, 0, 0], [0, 0, 1]]
autopep8 -i on that file

2017-11-30 18:29 UTC, fweik commented
/builds/espressomd/espresso/src/python/espressomd/utils.pyx:243:35: undeclared name not builtin: nest_level

2017-12-01 09:47 UTC, fweik commented
Not sure if I messed up the merge or if this stuff was broken before, feel free to reset to a8e6367.

2017-12-04 11:25 UTC, KaiSzuttor approved these changes

2017-12-04 11:27 UTC, fweik approved these changes

2017-12-04 13:02 UTC, merged