Remove bjerrum length n from long range interactions
espressomd/espresso pull request #1664
Opened 2017-11-25 19:53 UTC by RudolfWeeber

Fixes #1382 

This makes the long range interactions independent of the thermostat, by switching from the bjerrum length as an argument to the Coulomb constant
C=1/(4pi epsilon_0 epsilon_r) =l_B *kT

This also gets rid of the effect that the meaning of the Bjerrum length silently changes to the Coulomb constant, when the temperature is set to zero, and back to Bjerrum length, when kT>0 again.

This PR updates the core and interface for all electrostatic and magnetostatic interactions and electrokinetics as well as the test suite and samples (in so far as they are running)
Also done are the docs of those interactions that have up-to-date python-based docs.
The EK docs (currently being converted to Py by @rempferg ) are untouched.
The tutorials are not updated. I suggest to defer those, until it is clear if the IPython-based ones are there in time for the release.

2017-11-27 08:59 UTC, KonradBreitsprecher reviewed
Pretty complete, some leftovers:
- inter.rst line 2178 Dipolar direct sum on gpu stil has bjerrum.
- prefactor appears twice in valid_keys dict in some places
- method declaration p3m_set_prefactor() in p3m.hpp
- Tutorials. I will take care of 02 charged systems. 05 and 07 also need changes

2017-11-27 08:59 UTC, KonradBreitsprecher commented on src/python/espressomd/magnetostatics.pyx
> +            return "prefactor", "alpha_L", "r_cut_iL", "mesh", "mesh_off", "cao", "inter", "accuracy", "epsilon", "cao_cut", "a", "ai", "alpha", "r_cut", "inter2", "cao3", "additional_mesh", "prefact
prefacor appears twice in valid_keys

2017-11-27 08:59 UTC, KonradBreitsprecher commented on src/python/espressomd/magnetostatics.pyx
> +                return ("prefactor", "prefactor")
prefactor appears twice

2017-11-27 08:59 UTC, KonradBreitsprecher commented on src/python/espressomd/magnetostatics.pyx
> +            return ("prefactor", "prefactor")
prefactor appears twice in valid_keys

2017-11-27 08:59 UTC, KonradBreitsprecher commented on src/python/espressomd/magnetostatics.pyx
> +            return ("prefactor", "prefactor", "n_replica")
prefactor appears twice in valid_keys

2017-11-27 08:59 UTC, KonradBreitsprecher commented on src/core/p3m.hpp
missing void p3m_set_prefactor(void) ?

2017-11-27 11:53 UTC, pkreissl commented on doc/sphinx/inter.rst
> +   C=\frac{1}{4pi \epsilon_0 \epsilon_r}
`\pi`

2017-12-08 11:21 UTC, KaiSzuttor commented on testsuite/electrostaticInteractions.py
> +        self.assertTrue(np.allclose(u_dh_core,
numpy.testing.assert_allclose

2017-12-08 12:56 UTC, RudolfWeeber commented
Fixes #600

2017-12-21 15:34 UTC, fweik requested changes
Aside from the obvious merge leftovers, this can be merged.

2017-12-21 15:34 UTC, fweik commented on samples/visualization_mmm2d.py
> +<<<<<<< HEAD
This looks wrong.

2017-12-21 15:34 UTC, fweik commented on src/core/interaction_data.cpp
> +  if (prefactor < 0.0) {
Do we really want to have that limitation? At least the gpu p3m works fine with negative prefactor (=gravity).

2017-12-21 15:34 UTC, fweik commented on src/python/espressomd/magnetostatics.pyx
> +                Magnetoztatics prefactor
Typo

2017-12-22 12:43 UTC, merged