close threads if window is closed with x-button
espressomd/espresso pull request #1720
Opened 2017-12-15 15:23 UTC by KonradBreitsprecher

Calls `os._exit()`  if window is closed via x-button.

2017-12-15 16:47 UTC, KaiSzuttor requested changes

2017-12-15 16:47 UTC, KaiSzuttor commented on src/python/espressomd/visualization_opengl.pyx
> +        def closeWindow():
can you please rename pep8 conform? maybe also other functions in that module

2017-12-18 13:01 UTC, KonradBreitsprecher commented
@KaiSzuttor pep8 it is

2017-12-18 13:10 UTC, fweik approved these changes

2017-12-18 13:32 UTC, KaiSzuttor approved these changes

2017-12-19 11:26 UTC, merged