Random pairs
espressomd/espresso pull request #1739
Opened 2017-12-22 15:13 UTC by fweik

Added test to check pair finding with a random position set.

2018-01-17 11:04 UTC, fweik commented
@KaiSzuttor

2018-01-17 13:21 UTC, KaiSzuttor requested changes

2018-01-17 13:21 UTC, KaiSzuttor commented on src/core/debug.cpp
> +  for (int c = 0; c < local_cells.n; c++) {
please add some comments what is being checked here

2018-01-17 13:21 UTC, KaiSzuttor commented on src/core/domain_decomposition.cpp
> +        if (PERIODIC(dir) || !boundary[2 * dir]) {
what is this check for?

2018-01-17 13:21 UTC, KaiSzuttor commented on src/core/domain_decomposition.cpp
> +                       "%d: dd_append_particles: Appen Part id=%d to cell %d cpos %d %d %d\n",
typo

2018-01-17 13:21 UTC, KaiSzuttor commented on testsuite/random_pairs.py
> +from __future__ import print_function
autopep8 -i on that file

2018-01-17 13:21 UTC, KaiSzuttor commented on testsuite/random_pairs.py
> +class RandomPairTest(ut.TestCase):
docstring for the test class

2018-01-19 11:48 UTC, fweik commented
@KaiSzuttor Fixed the issues.

2018-01-22 17:43 UTC, KaiSzuttor approved these changes

2018-01-23 10:46 UTC, merged