Bh gpu
espressomd/espresso pull request #1766
Opened 2018-01-15 14:41 UTC by fweik

Fixes #

Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2018-01-15 23:08 UTC, hmenke requested changes

2018-01-15 23:08 UTC, hmenke commented on src/core/actor/DipolarBarnesHut.cpp
> +        free(dipolarBarnesHut);
Mixing `new`/`delete` with `malloc`/`free` will most likely lead to a segfault.

2018-01-15 23:08 UTC, hmenke commented on src/core/actor/DipolarBarnesHut.cpp
> +DipolarBarnesHut *dipolarBarnesHut=0;
`nullptr`

2018-01-15 23:08 UTC, hmenke commented on src/core/actor/DipolarBarnesHut.cpp
> +    dipolarBarnesHut =new DipolarBarnesHut(espressoSystemInterface, epssq, itolsq);
Why is there a global (!) pointer (!) to the method?  This design looks very broken.

2018-01-16 10:18 UTC, fweik commented
@hmenke please commont on #1273, whis was just to trigger the CI.

2018-01-16 10:18 UTC, closed without merging

2018-01-16 13:59 UTC, psci2195 commented
Thanks, I agree with @hmenke comments and will introduce required changes within #1273 

Please also note, that I've originally just cloned the existing actor architecture: https://github.com/espressomd/espresso/blob/python/src/core/actor/DipolarDirectSum.cpp
Hence, it may require same improvements. I'll open the separate issue/PR after the BH one completion to merge same improvements unless someone wish to work on the DDS actor.