MPI-IO Python Bindings
espressomd/espresso pull request #1789
Opened 2018-01-30 09:45 UTC by hirschsn

This PR implements python bindings for the bare MPI-IO functions in ESPResSo.

Since we came up with this deficit during our meeting last week and I had this interface lying around for quite some time, I decided to open a PR.

Description of changes:
 - Add a python interface for MPI-IO functionality in the core.

If it is decided that we want to merge this upstream, I can write docs etc.

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2018-01-30 13:01 UTC, KaiSzuttor requested changes
Looks good to me besides the comments. In the long run you may want to check using h5md. But there you would have to implement a reader, different story.

2018-01-30 13:01 UTC, KaiSzuttor commented on src/python/espressomd/io/mpiio.py
> +            print "[MPI-IO] Need to supply output prefix via 'prefix' kwarg."
``` python
raise ValueError("...")
```

2018-01-30 13:01 UTC, KaiSzuttor commented on src/python/espressomd/io/mpiio.py
> +            print "[MPI-IO] No output fields chosen. Not performing any write."
raise

2018-01-30 13:01 UTC, KaiSzuttor commented on src/python/espressomd/io/mpiio.py
> +            print "[MPI-IO] Need to supply output prefix via 'prefix' kwarg."
raise

2018-01-30 13:01 UTC, KaiSzuttor commented on src/python/espressomd/io/mpiio.py
> +            print "[MPI-IO] No output fields chosen. Not performing any read."
raise

2018-01-30 13:01 UTC, KaiSzuttor commented on src/core/mpiio.cpp
> +  set_resort_particles(Cells::RESORT_GLOBAL);
Can you please move all corresponding files into the io directory.

2018-01-30 13:01 UTC, KaiSzuttor commented on src/python/espressomd/io/mpiio.py
> +                   Common prefix for the filenames.
just to be picky... please align the explanation with the type description above

2018-02-02 11:52 UTC, hirschsn commented
Moved the files, put in appropriate python errors, removed the old mpi call stuff from `communication.[ch]pp` and added and fixed the documentation.

2018-02-02 12:34 UTC, KaiSzuttor commented on doc/sphinx/io.rst
> +outputs data in a *machine dependant format* but has write and read
type dependant

2018-02-02 12:34 UTC, KaiSzuttor commented on doc/sphinx/io.rst
> +To read these in again, simply call ``mpiio.read``. It has the same signature as
can you please directly reference the method by using ```:mod:`espressomd.io.mpiio.read` ```

2018-02-05 12:44 UTC, hirschsn commented
Thanks for looking over the patches, again! Fixed both problems.

2018-02-06 12:42 UTC, KaiSzuttor approved these changes

2018-02-06 12:43 UTC, KaiSzuttor commented
Could you please merge the current python branch?

2018-02-07 11:46 UTC, KaiSzuttor commented
``` bash
ImportError: /builds/espressomd/espresso/build/src/script_interface/libEspressoScriptInterface.so.4: undefined symbol: _ZN5Mpiio22mpi_mpiio_common_writeEPKcj
```

2018-02-07 11:55 UTC, hirschsn commented
Sorry, forgot to include the changes to CMakeLists.txt in one of the commits.

2018-02-14 10:28 UTC, KaiSzuttor approved these changes

2018-02-15 14:53 UTC, merged