Added code comments to the python interface of ek and lb boundaries a…
espressomd/espresso pull request #1818
Opened 2018-02-02 12:42 UTC by itischler

Fixes #1117

Description of changes:
 - Documentation comments on lbboundary.py
 - Documentation comments on ekboundary.py
 - Documentation comments on electokinetics.pyx

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2018-02-02 13:02 UTC, KaiSzuttor requested changes

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/ekboundaries.py
> +    Creates a set of electrokinetics boundaries.
newline after that line

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/ekboundaries.py
> +        or a valid set of parameters to create a boundary.
newline after that line

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/ekboundaries.py
> +                     The boundary to be removed from the set.
newline after that line

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/ekboundaries.py
> +    Creates a EK boundary.
newline after that line

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/electrokinetics.pyx
> +        Creates the electrokinetic method using the GPU unit.
newline after that line

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/electrokinetics.pyx
> +            Checks if the parameters for "stencil" and "fluid_coupling" are valid.
newline after that line

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/electrokinetics.pyx
> +            Retruns the valid options used for the electrokinetic method.
typo returns

newline after that line

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/electrokinetics.pyx
> +            Retruns the nessesary options to initialize the electokinetic method.
typo returns

newline after that line

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/electrokinetics.pyx
> +            Retruns the default paramters.
typo returns

newline after that line

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/electrokinetics.pyx
> +
no newlines between parameters necessary

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/electrokinetics.pyx
> +            Prints out the parameters of the electrokinetic system.
please add newlines at the end of every docstring

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/electrokinetics.pyx
> +            Returns the valid keys for the species
please end with a period

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/electrokinetics.pyx
> +            path : :obj: `string`
no space between obj and the ticks

2018-02-02 13:02 UTC, KaiSzuttor commented on src/python/espressomd/lbboundaries.py
> +            lbboundary : :obj: `LBBoundary`
is a link generated here? please check, if not you have to provide the full path

2018-02-02 13:16 UTC, KaiSzuttor commented
please pull in the current python branch, your base branch seems *very* old

2018-02-06 15:47 UTC, fweik commented
@KaiSzuttor please merge if you're happy, your points seem to by mostly addressed.

2018-02-06 17:30 UTC, merged