Vtf doc
espressomd/espresso pull request #1829
Opened 2018-02-02 17:34 UTC by davidsean

Fixes #1807

Description of changes:
 - updated text from TCL
 - made VTF id's continuous and increasing
 - added map between VTF and espresso PID

PR Checklist
------------
 - [x] Tests?
   - [x] Interface
   - [ ] Core 
 - [x] Docs?

2018-02-02 17:40 UTC, KaiSzuttor requested changes

2018-02-02 17:40 UTC, KaiSzuttor commented on doc/sphinx/io.rst
> +    # ... set system properties like box_l or timestep here ...
time_step

2018-02-02 17:40 UTC, KaiSzuttor commented on doc/sphinx/io.rst
> +Creating files in these formats from within is supported by the commands ``writevsf``
please link to the in-source documentation with ```:meth:`espressomd.io.writevsf` ``` or similar

2018-02-02 17:40 UTC, KaiSzuttor commented on doc/sphinx/io.rst
> +    system = espressomd.System()
please use the new syntax for setting up a system with the box_l parameter

2018-02-02 17:40 UTC, KaiSzuttor commented on doc/sphinx/io.rst
> +    system = espressomd.System()
please use new syntax

2018-02-02 17:40 UTC, KaiSzuttor commented on doc/sphinx/io.rst
>  .. _writevcf\: Writing the coordinates:
does this link work without the ticks?

2018-02-02 17:40 UTC, KaiSzuttor commented on src/python/espressomd/io/writer/vtf.py
> +    types : str
please use ```:obj:`str` ```

2018-02-04 15:33 UTC, davidsean commented on doc/sphinx/io.rst
>  .. _writevcf\: Writing the coordinates:
I checked and it seems fine

2018-02-06 12:45 UTC, KaiSzuttor commented
something seems to be wrong with python3 compatibility

2018-02-06 12:48 UTC, RudolfWeeber commented
Once Py3 is sorted out, this can be merged.

2018-02-06 14:54 UTC, merged