Mindist for constraints
espressomd/espresso pull request #1843
Opened 2018-02-10 20:47 UTC by davidsean

Fixes #

Description of changes:
 - wrote a core mindist for constraints
 - python interface
 - updated documentation
 - fixed a warmup problem for the constraints sample
 - CI tests for wall and cylinder

PR Checklist
------------
 - [x] Tests?
   - [x] Interface
   - [x] Core 
 - [x] Docs?

2018-02-11 10:14 UTC, fweik requested changes
There are several issues with this:
- It uses the shape contained in the constraint with unfolded coordinates where the shape expects folded positions. (positions in partCfg are unfolded)
- The tests apparently did not catch this.
- It uses partCfg that can only be used on the head node on all nodes.

2018-02-11 10:14 UTC, fweik commented on src/core/constraints/ShapeBasedConstraint.cpp
> +double ShapeBasedConstraint::mindist() {
This is parallel code (it runs on all nodes in synchronous mode), so you can't use `partCfg`, as it exists only on the head node. There is also no need, as your algorithm does not need global information, you can run it on each node locally and then reduce the local results to the master. Also folded coordinates should be used with the shape, but particles in partCfg have folded coordinates. So you could do something along the lines of

```c++
auto & parts = local_cells.particles();

auto const local_mindist = std::accumulate(parts.begin(), parts.end(), std::numeric_limits<double>::infinity(), [this](double min, Particle const& p) {
  if(!checkIfInteraction(...))
    return min;
  else  {
     double dummy[3], dist;
     m_shape->calculate_dist(folded_position(p).data(), &dist, dummy); 

     return std::min(min, dist);
   });

   double global_min;
   boost::mpi::reduce(comm_cart, local_min, global_min, std::min, 0);

   return global_min;
}
```  
}

2018-02-11 10:56 UTC, RudolfWeeber commented
The python method in analysis.pyx is called min_dist.
I'm also not sure, min_dist is actually what it does. For a sphere,
e.g., I think it takes the vector which is perpendicular to the
surface of the sphere (@pkreissl?).

2018-02-12 09:41 UTC, jonaslandsgesell commented on testsuite/constraint_shape_based_wall.py
> +        wall_xy = system.constraints.add(constraint_wy)
Why did you exchange the naming of the wall variables? The old convention was the following: if the normal vector is in y direction (0,1,0) then the wall lies parallel to the xz plane and therefore the wall is named wall_xz

2018-02-12 10:39 UTC, davidsean commented on testsuite/constraint_shape_based_wall.py
> +        wall_xy = system.constraints.add(constraint_wy)
I had it follow the naming convention for walls and shape where the last character gives the normal. I did not realize xz meant the xz plane. I don't care which convention is chosen, however constraint_wy should then be constraint_xz and the shape wy should be xz to be consistent.

2018-02-12 12:20 UTC, fweik approved these changes

2018-02-12 12:20 UTC, merged