warned about the usage of the word catalyst in feature swimmer_reaction
espressomd/espresso pull request #1895
Opened 2018-03-08 09:53 UTC by jonaslandsgesell

2018-03-08 10:51 UTC, mkuron commented
We just discussed this with @jdegraaf. Please rename everything to "reactive swimmer". It does model a catalyst in a certain abstract way. It certainly is not chemically or thermodynamically correct, so it should only be understand for its intended purpose.

This paragraph is a bit too defamatory for my taste and not entirely true:

> Be careful the model makes far-fetched usage of the word catalyst. This usage of the word cannot be brought into agreement with the correct usage of the word catalyst.

It is fine to point out that this feature has only a very narrow application (i.e. a specific catalytic swimmer model). But it is definitely not as useless as that paragraph suggests.

2018-03-08 11:17 UTC, fweik commented
Currently there are two implementations, the old one by Georg and the newer default one by @hmenke and @jdegraaf. Do we need to keep both? In the code there are comments that suggest that the original one is flawed.

2018-03-08 11:22 UTC, jdegraaf commented
Both have their weaknesses, but the former more so than the latter. If you
wish to clean up the code, I think getting rid of the former is acceptable,
as I will not be using it anymore and I don't know anyone who does, except
maybe Pierre?

On 8 March 2018 at 12:17, Florian Weik <notifications@github.com> wrote:

> Currently there are two implementations, the old one by Georg and the
> newer default one by @hmenke <https://github.com/hmenke> and @jdegraaf
> <https://github.com/jdegraaf>. Do we need to keep both? In the code there
> are comments that suggest that the original one is flawed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/pull/1895#issuecomment-371458542>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACuLn9lQGBJKFZs3h2QVKpzuXAH_yP2Rks5tcRNfgaJpZM4Siacq>
> .
>

2018-03-12 15:47 UTC, pdebuyl commented
I don't use ESPResSo's swimmer features myself. I tend to use the purpose-built [RMPCDMD](https://github.com/pdebuyl-lab/RMPCDMD) code for that :-)

I found easily the catalytic feature that has the tutorial. Where is the other one in the docs? I would consider it more consistent for end-users to have only one of the features present. But it also depends on the testing and on the use of the features. Do you have an idea about this?

If it is of interest, I know well the MPCD-type techniques to make chemical nanomotors move in the case you'd like me to have a look at the docs. (after clearing up what stays and what doesn't, of course).

2018-03-13 10:48 UTC, jdegraaf commented
Hi Pierre,

After much discussion with Jonas the last time, we moved the other
catalytic feature out of the documentation and made it the standard to
invoke the swap move. You can still access it by uncommenting bits of the
interface, I believe. Though Henri might know more, as he is the one that
implemented this. The original behavior is, I believe, similar to the one
you are using.

Best Wishes,

Joost

On 12 March 2018 at 16:47, Pierre de Buyl <notifications@github.com> wrote:

> I don't use ESPResSo's swimmer features myself. I tend to use the
> purpose-built RMPCDMD <https://github.com/pdebuyl-lab/RMPCDMD> code for
> that :-)
>
> I found easily the catalytic feature that has the tutorial. Where is the
> other one in the docs? I would consider it more consistent for end-users to
> have only one of the features present. But it also depends on the testing
> and on the use of the features. Do you have an idea about this?
>
> If it is of interest, I know well the MPCD-type techniques to make
> chemical nanomotors move in the case you'd like me to have a look at the
> docs. (after clearing up what stays and what doesn't, of course).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/pull/1895#issuecomment-372357483>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACuLn2roWJ22uWnXATOeXryIBSc3PObYks5tdph7gaJpZM4Siacq>
> .
>

2018-03-23 14:02 UTC, fweik commented
@jonaslandsgesell please apply the name-change everywhere.

2018-03-29 14:54 UTC, jonaslandsgesell commented
Is the name swimmer_reaction ok? or do you want the feature to be named reactive_swimmer?

2018-03-29 14:56 UTC, jdegraaf commented
Hello Jonas,

I think swimmer_reaction is better, since reactive_swimmer might be
associated with the idea that this naturally has self-propulsion in it,
which it does not.

Best Wishes,

Joost

On 29 March 2018 at 16:54, Jonas Landsgesell <notifications@github.com>
wrote:

> Is the name swimmer_reaction ok? or do you want the feature to be named
> reactive_swimmer?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/pull/1895#issuecomment-377261696>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACuLnzy94DBa395cgJd0g5sTfJOub31bks5tjPWjgaJpZM4Siacq>
> .
>

2018-04-03 13:18 UTC, jonaslandsgesell commented
test_checkpoint fails here although not touched

2018-04-13 09:37 UTC, fweik approved these changes

2018-04-13 09:43 UTC, fweik requested changes

2018-04-13 09:43 UTC, fweik commented on src/core/particle_data.cpp
> +  particle_node.erase(particle_node_iterator);
Do `erase(p_id)`, your code is invalid if `p_id` is not in the map.

2018-04-13 11:46 UTC, fweik approved these changes

2018-04-13 11:48 UTC, merged