DD resort refactor
espressomd/espresso pull request #1923
Opened 2018-03-22 18:55 UTC by fweik

Description of changes:
 - DD resort refactored into multiple functions and simplified.
 - Fixed layered with full periodic boundaries (hopefully)
 - Extended pair finding test
 - Resort now works with folded coords
 - Moved local sort to cells level
 - Moved particle position reset from short-range loop (?) to sorting code.
 - Minor performance improvements.

2018-09-27 07:13 UTC, KaiSzuttor requested changes

2018-09-27 07:13 UTC, KaiSzuttor commented on src/core/cells.cpp
> +
could you please add docstrings to the new functions?

2018-09-27 07:13 UTC, KaiSzuttor commented on src/core/cells.cpp
> +  if (0 != displaced_parts.n) {
this could be a function

2018-09-27 07:13 UTC, KaiSzuttor commented on src/core/domain_decomposition.cpp
> +void move_left_or_right(ParticleList &src, ParticleList &left,
please add a docstring here too

2018-09-28 09:52 UTC, fweik commented
@KaiSzuttor

2018-10-16 19:48 UTC, fweik commented
@RudolfWeeber, we maybe should also look at some benchmarks to check that I did not screw up too much. Also I think we should find some permanent solution for the NPT test, it has a false positive every time the order the PRNG is applied changes. This is not what it is supposed to check.

2018-10-17 19:03 UTC, fweik commented
@RudolfWeeber ready from my side. The NPT issue remains, but I think it's a false positive.

2018-11-22 11:37 UTC, RudolfWeeber commented
I think, this PR can be merged.

2018-11-26 13:38 UTC, merged