extended widom insertion to allow the user to determine multiple exce…
espressomd/espresso pull request #1964
Opened 2018-05-03 08:28 UTC by jonaslandsgesell

…ss chemical potentials at once

2018-05-03 12:20 UTC, fweik requested changes

2018-05-03 12:20 UTC, fweik commented on src/core/reaction_ensemble.cpp
> +void WidomInsertion::add_reaction (double Gamma, const std::vector<int> &_reactant_types,
Please stick to the naming convention.

2018-05-03 12:37 UTC, jonaslandsgesell commented on src/core/reaction_ensemble.cpp
> +void WidomInsertion::add_reaction (double Gamma, const std::vector<int> &_reactant_types,
Which one? https://github.com/espressomd/espresso/wiki/Naming-conventions-and-folder-structure I do not see which convention listed there would apply.

2018-05-03 12:53 UTC, jonaslandsgesell commented on src/core/reaction_ensemble.cpp
> +void WidomInsertion::add_reaction (double Gamma, const std::vector<int> &_reactant_types,
Seems like you refer to https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

2018-05-03 13:19 UTC, fweik commented
You also have to rename `Gamma` to `gamma`.

2018-05-03 19:38 UTC, fweik approved these changes

2018-05-23 08:20 UTC, jonaslandsgesell commented
Also fixes #1981.

2018-05-23 09:17 UTC, merged