LB viscous coupling test
espressomd/espresso pull request #1996
Opened 2018-06-01 09:22 UTC by KaiSzuttor

Description of changes:
 - tests the viscous force on a particle for CPU and GPU LB

2018-06-01 10:34 UTC, KaiSzuttor commented
It seems like the interpolated velocity is lacking a factor of ```agrid*agrid```. If I divide the interpolated velocity by that factor, the results are correct, but I have no glue where it comes from.

2018-06-04 20:50 UTC, RudolfWeeber commented
So, single node and interpolated velocities agree
lbf[0,0,0],lbf.get_interpoalted_velocity([agrid/2]*3)
But the setters and getters 
        self.lbf[0, 0, 0].velocity = v_fluid
        np.testing.assert_allclose(v_fluid,self.lbf.get_interpolated_velocity(self.system.part[0].pos),atol=1E-5)
        np.testing.assert_allclose(v_fluid,self.lbf[0,0,0].velocity,atol=1E-5)
In the code lb_node_set_u and ..._get_u
Getter: lb -> md
p_u[0] = j[0] / rho * lbpar.agrid / lbpar.tau;

Setter: md -> lb
j[0] = rho * u[0] * lbpar.tau * lbpar.agrid;

Personally, I beleave the getter more, but that may not mean much./

2018-06-04 21:16 UTC, fweik commented
The getter is not correct, it assumes that the `rho` returned from `mpi_recv_fluid` does contain the density, but the getter for `rho`, and the definition of the eq populations in the core, suggests that it actually is the mass of the cell, not the density.

2018-06-05 05:54 UTC, KaiSzuttor commented
> So, single node and interpolated velocities agree
You mean disagree?

2018-06-05 08:10 UTC, KaiSzuttor commented
So it turned out that the interpolated velocity was correct :dizzy_face:, but the setter for the node velocity was wrong. I added a test for the setting/getting of node velocity.

2018-06-05 08:12 UTC, RudolfWeeber commented
On Mon, Jun 04, 2018 at 10:54:32PM -0700, Kai Szuttor wrote:
> > So, single node and interpolated velocities agree
> You mean disagree?
Agree. They also use the same getter.

The inconsistency between setter and getter is an agrid^2.

2018-06-05 09:33 UTC, hmenke requested changes

2018-06-05 09:33 UTC, hmenke commented on maintainer/configs/maxset.hpp
> +//#define LB_BOUNDARIES
Are you sure about that?

2018-06-05 09:41 UTC, KaiSzuttor commented on maintainer/configs/maxset.hpp
> +//#define LB_BOUNDARIES
No its a usual ```git commit -am``` relict

2018-06-05 10:41 UTC, hmenke commented
I just git blamed `lb_lbnode_set_u`.  Turns out this error is 7 years old!  Here is the commit: https://github.com/espressomd/espresso/commit/c97f7319eba76fecd0b4471ea575d3f142eb135c

2018-06-05 11:04 UTC, fweik commented
LGTM when Henri's comment is addressed.

2018-06-05 13:42 UTC, merged