Mass and rinertia tests refactoring
espressomd/espresso pull request #2021
Opened 2018-06-08 21:37 UTC by psci2195

Fixes #1905
Test refactoring according to [advice](https://github.com/espressomd/espresso/commit/5ba2c41a3d8e391d072f13bc1f71f6c706422f49#r28083156)/[advice](https://github.com/espressomd/espresso/pull/1757#issuecomment-392322098) from @KaiSzuttor and @RudolfWeeber 
Description of changes:
 - Refactored the naming and comments
 - The test cases loop has been refactored into the separate test cases
 - A code duplication is reduced
 - A code size is reduced by a removing of unnecessary type conversions
 - More advanced `unittest` usage

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2018-06-11 12:23 UTC, KaiSzuttor requested changes
Thanks alot @psci2195, it's a lot more readable now! To make me even more happy, could you please address my comments?

2018-06-11 12:23 UTC, KaiSzuttor commented on testsuite/mass-and-rinertia_per_particle.py
> +                        sigma2_tr[k] += self.D_tran_p_validate[k,
could you please add a reference for the formula you compare to

2018-06-11 12:23 UTC, KaiSzuttor commented on testsuite/mass-and-rinertia_per_particle.py
> +    def fluctuation_dissipation(self,n):
could you please name the methods according to what they do, like ```check_fluctuation_dissipation``` or ```set_xy_variable```

2018-06-11 12:23 UTC, KaiSzuttor commented on testsuite/mass-and-rinertia_per_particle.py
> +        self.J = (0.2 + np.random.random(3)) * 7.0
where do the magic ```0.2``` and ```0.7``` come from? In general magic number should have a descriptive name

2018-06-11 12:23 UTC, KaiSzuttor commented on testsuite/mass-and-rinertia_per_particle.py
> +    def langevin_global_defaults(self):
also here: please name methods according to what they do

2018-06-11 12:23 UTC, KaiSzuttor commented on testsuite/mass-and-rinertia_per_particle.py
> +    def fluctuation_dissipation_param_setup(self,n):
could you please use the numpy-style in-code documentation that is used for python functions in espresso and describe what the argument to the function means and what type it has

2018-06-11 12:23 UTC, KaiSzuttor commented on testsuite/mass-and-rinertia_per_particle.py
> +        print("-------------------------------------------------------------")
Please avoid print statements in testcases.

2018-06-11 22:52 UTC, psci2195 commented
@KaiSzuttor thanks for an useful review. I've implemented changes according to each bullet raised by you.

2018-06-12 04:53 UTC, KaiSzuttor approved these changes

2018-06-12 08:43 UTC, merged