Reaction ensemble vs constant pH tutorial written by Andrea
espressomd/espresso pull request #2050
Opened 2018-07-09 10:57 UTC by atagliabue

Instead of PR #2037

2018-07-09 16:13 UTC, KonradBreitsprecher requested changes
I read it until the last comment of mine,
you should look over it once more 
and correct for typos and script issues. Copy-paste the snippets and get it running for a final test. Also state which features are needed (myconfig.hpp).

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +while second part will consider a polyelectrolyte chain formed by a series of titratable monomers bonded together.
...while **the** second part...

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +\section{First part: homogeneous aqueous solution of acidic species}
"First part" (as section 3) confused me a bit, better call it "Example one"

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +\section{Second part: linear weak polyelectrolyes}
"Example two"

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +system = espressomd.System(box_l=[box_l]*3)
box_l defined only afterwards..

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +\np.random.seed(seed=system.seed)
\np

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +mode=="reaction_ensemble"
== ?

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +Weak polyelectrolytes are a family of responsive materials whose application spans the range from flocculation-induced water purification to tissue targeted drug delivery of expensive or cytotoxic me
their topology **is** markedly modifying

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +Here we're going to study the titration curves of a linear weak polyelectrolytes composed by 50 titratable units with both Reaction Ensemble and Constant pH methods. In this case, we'll enable electr
of linear weak polyelectrolytes

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +system.actors.add(p3m)
Script snippet in wrong order. Also, state here what is needed from the script in part one.

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +# setup partilcles
Typo

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +for i in range(N0):
N0 not defined

2018-07-09 16:13 UTC, KonradBreitsprecher commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +# when you have to handle with many differet type of species in your system,
Typo

2018-07-09 16:40 UTC, atagliabue commented
Hallo Konrad, thanks for your quick reply. Scripts should be working (but I will check another time tomorrow), maybe I mixed some lines from the script file to the tutorial pdf. I'll try to make it more clear and to fix all the typos. Thanks

2018-07-14 12:24 UTC, davidsean requested changes

2018-07-14 12:24 UTC, davidsean commented on doc/tutorials/10-reaction_ensemble/scripts/RE_vs_cpH.py
> +    RE.reaction()
I think it would be better to use
`RE.reaction(reaction_steps=100)` and to remove the i%100 part, (also decrease the range accordingly)

2018-07-14 12:24 UTC, davidsean commented on doc/tutorials/10-reaction_ensemble/scripts/RE_vs_cpH.py
> +alpha_err = np.std(alpha)/len(alpha)
you probably wanted to divide by the squart-root: `alpha_err = np.std(alpha)/sqrt(len(alpha))`,

2018-07-16 07:50 UTC, atagliabue commented on doc/tutorials/10-reaction_ensemble/scripts/RE_vs_cpH.py
> +alpha_err = np.std(alpha)/len(alpha)
Of course, thanks

2018-07-16 12:09 UTC, pkreissl reviewed
Please use `autopep8 -i` on the tutorial python file.

2018-07-24 09:51 UTC, pkreissl commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +Please notice that the order in which the species are written in reactants and products lists is very important because, when a reaction is performed, the first species in the reactants list is repla
[...] while if the products list **has** more species than the reactants list, **product** molecules [...]

2018-07-25 11:20 UTC, fweik commented on doc/tutorials/10-reaction_ensemble/10-reaction_ensemble.tex
> +system.actors.add(p3m)
@KonradBreitsprecher is this still an issue?

2018-08-15 13:48 UTC, RudolfWeeber commented
What is the state of this pr?

2018-08-16 13:35 UTC, jonaslandsgesell commented
It s fine for now. As some bachelor students will try to do it, it will become apparent where the weaknesses are educationalwise. Physicswise the content is good.

2018-08-16 13:35 UTC, jonaslandsgesell approved these changes

2018-08-16 13:42 UTC, merged