Draft release notes
espressomd/espresso pull request #2122
Opened 2018-07-31 08:33 UTC by RudolfWeeber

Fixes #2095

2018-07-31 08:38 UTC, KaiSzuttor requested changes

2018-07-31 08:38 UTC, KaiSzuttor commented on NEWS
> +Please note that, starting from ESPResSo 4.0, enabling additoinal features in myconfig.hpp no longer changes the behavior of a simulation scripts. Features such as particle rotation and virtual sites
typo

2018-07-31 08:38 UTC, KaiSzuttor commented on NEWS
> +* GPU-accelerated direct summation of dipolar interactoins under open boundary conditions
typo

2018-07-31 08:38 UTC, KaiSzuttor commented on NEWS
> +* Espresso now depends on the Boost library including Boost-Mpi and a C++11 capable compiler
didn't we want to switch to c++14?

2018-07-31 08:41 UTC, fweik commented
Yes, but not for the release.

On Tue, Jul 31, 2018, 10:38 Kai Szuttor <notifications@github.com> wrote:

> *@KaiSzuttor* requested changes on this pull request.
> ------------------------------
>
> In NEWS
> <https://github.com/espressomd/espresso/pull/2122#discussion_r206440459>:
>
> > -* Using the rotation_per_particle feature, it is now possible to switch the integration of the rotational degrees of freedom per individual axis in the particle's body-fixed frame.
> -* The rotational degrees of freedom of virtual sites is now integrated. Virtual sites no longer use the quaternion attributes to store their relative orientation
> +ESPResSo 4.0 is the first release of ESPResSo with a Python interface.
> +I.e., the language in which simulation scripts are written is now Python,
> +and support for the TCL-Interface has been dropped.
> +We recommend all users switch to ESPResSo 4.0, there will be no more fixes to
> +TCL-based versions.
> +
> +Transitioning from TCL-based versions
> +-------------------------------------
> +
> +The following can serve as a starting point for the new interface:
> +* The "Introduction" chapter in the user's guide
> +* The tutorials in the /doc/tutorials directory of the distribution.
> +
> +Please note that, starting from ESPResSo 4.0, enabling additoinal features in myconfig.hpp no longer changes the behavior of a simulation scripts. Features such as particle rotation and virtual sites have to be activated explicitly in the simulation scripts.
>
> typo
> ------------------------------
>
> In NEWS
> <https://github.com/espressomd/espresso/pull/2122#discussion_r206440625>:
>
> > +-------------------------------------
> +
> +The following can serve as a starting point for the new interface:
> +* The "Introduction" chapter in the user's guide
> +* The tutorials in the /doc/tutorials directory of the distribution.
> +
> +Please note that, starting from ESPResSo 4.0, enabling additoinal features in myconfig.hpp no longer changes the behavior of a simulation scripts. Features such as particle rotation and virtual sites have to be activated explicitly in the simulation scripts.
> +
> +New features:
> +-------------
> +* Reaction ensemble method for the modelling of chemical reactions
> +* Polarisable particles via the Drude-oscillator scheme
> +* Steepest-descent energy minimization scheme
> +* Methods for active particles (swimmer_reaction, dipolar swimmers)
> +* GPU-accererated P3M method for electrostatic interactions
> +* GPU-accelerated direct summation of dipolar interactoins under open boundary conditions
>
> typo
> ------------------------------
>
> In NEWS
> <https://github.com/espressomd/espresso/pull/2122#discussion_r206440892>:
>
> >
> -Changes visible for developers
> -------------------------------
> -* CMake build system
> +* When the ROTATION feature is compiled in, the rotation of a particle around each of its Cartesian axes in the body-fixed frame can be enabled
> +* The rotational degrees of freedom of virtual sites is now integrated. Virtual sites no longer use the quaternion attributes to store their relative orientation
> +* Alternatively, the orientation of the virtual site can be specified relative to that of the particle it is derived from.
> +* The random number generator was changed to Mersenne Twister as implemented by C++11.
> +* Espresso now depends on the Boost library including Boost-Mpi and a C++11 capable compiler
>
> didn't we want to switch to c++14?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/pull/2122#pullrequestreview-141851373>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA2i3y3_fpFbHqLPULhSX71SCFp6UcRoks5uMBdrgaJpZM4Vn0uU>
> .
>

2018-07-31 09:54 UTC, KaiSzuttor submitted a review, later dismissed

2018-07-31 09:54 UTC, KaiSzuttor commented on NEWS
> +* The memd/meggs electrostatic solver
typo maggs

2018-07-31 09:54 UTC, KaiSzuttor commented on NEWS
> +* The Chan Shen lattice Boltzmann extension
this is still in for GPU LB

2018-07-31 09:54 UTC, KaiSzuttor commented on NEWS
> +
what about lees edwards?

2018-07-31 09:54 UTC, KaiSzuttor commented on NEWS
> +* The lj_angle and angledist (not-qutie)-pair potentials
typo?

2018-07-31 09:54 UTC, KaiSzuttor commented on NEWS
> +  diffusion_profile, cwvac, p_isnt, ..._mol, cel_gpb, dipmom_normal, MSd, angularmomentum, cluster_size_dist, mol, lipid_orient_order, get_lipid_oriends, current, wall_stuff,
typo: p_inst, MSD, get_lipid_orients

2018-07-31 11:32 UTC, RudolfWeeber commented
LE was never part of an official release, afaik. Mentioned it anyway, now.
Gpu Shan Chen has no (finished) Python interface. We only test that it still builds.

2018-08-01 12:06 UTC, jonaslandsgesell requested changes

2018-08-01 12:06 UTC, jonaslandsgesell commented on NEWS
> +* Reaction ensemble method for the modelling of chemical reactions
The constant pH method is also implemented and differs in the acceptance probability. I think it is worth to note both methods here.

2018-08-20 09:10 UTC, RudolfWeeber commented
IBM and Object in Fluid

2018-08-20 11:12 UTC, RudolfWeeber commented
@fweik, from my side, everything is in. Merge, if you are happy with it.

2018-08-21 10:52 UTC, fweik commented
LGTM except for the two typos that kai pointed out.

2018-08-24 12:53 UTC, KonradBreitsprecher commented on NEWS
> +Removed featues
Typo featues

2018-08-27 06:02 UTC, hmenke commented on NEWS
> +* The Chan Shen lattice Boltzmann extension
~~Chan Shen~~ Shan Chen

2018-08-31 08:21 UTC, fweik commented on NEWS
> +  about 1% of the time and leak memory. (#2187, 2186)
The leak has been fixed. The failures still exist.

2018-08-31 14:53 UTC, fweik approved these changes

2018-09-01 09:29 UTC, merged