python: adding check for particle existence.
espressomd/espresso pull request #2151
Opened 2018-08-14 08:14 UTC by KaiSzuttor

Fixes #2150

2018-08-14 13:05 UTC, fweik requested changes

2018-08-14 13:05 UTC, fweik commented on src/python/espressomd/particle_data.pxd
> +    particle& get_particle_data(int id) except +
Must be `const &`.

2018-08-14 14:40 UTC, KaiSzuttor commented
hm... dejavu... we need cython 0.26 for this to work

2018-08-15 09:13 UTC, fweik commented
You can jsut remove the data member and call `get_particle_data` in the getters. That is the cleaner solution anyway

2018-08-15 19:00 UTC, fweik approved these changes

2018-08-15 19:29 UTC, merged