tutorial6: cone orientation
espressomd/espresso pull request #2202
Opened 2018-08-27 15:18 UTC by jngrad

Fixes cone issue in #2129

2018-08-27 15:32 UTC, mkuron requested changes

2018-08-27 15:32 UTC, mkuron commented on doc/tutorials/06-active_matter/SOLUTIONS/rectification_simulation.py
> +system.box_l = [length, diameter + 4, diameter + 4]
You deleted the RNG seeding and set the box length twice. Also in some of the other files.

2018-08-27 15:32 UTC, mkuron commented on doc/tutorials/06-active_matter/SOLUTIONS/rectification_geometry.py
> +system = espressomd.System(box_l=[length, dieameter + 4, diameter + 4])
typo in `diameter`. You didn't test the scripts after making your changes.

2018-08-27 15:32 UTC, mkuron commented on doc/tutorials/06-active_matter/EXERCISES/rectification_geometry.py
> +outdir = "./RESULTS_RECTIFICATION/"
Undo this change. Right now the template and the solution don't match.

2018-08-27 15:32 UTC, mkuron commented on doc/tutorials/06-active_matter/EXERCISES/rectification_geometry.py
> -
Restore this, I think it's still valid.

2018-08-27 15:32 UTC, mkuron commented on doc/tutorials/06-active_matter/SOLUTIONS/rectification_simulation.py
This doesn't belong here.

2018-08-27 15:32 UTC, mkuron commented on tools/blockfile.py
> +        sys.exit()
What happened here?

2018-08-27 16:32 UTC, jngrad commented
Something went wrong when merging with upstream, I reverted it. The [branch diff](https://github.com/jngrad/espresso/compare/517170998a6684863...jngrad:d482f419577d32e0193add) should be clean now.

Side note: `tools/blockfile.py` has Windows line feeds (CRLF) instead of Unix line feeds (LF), this can be confusing when doing merges.

2018-08-27 17:37 UTC, mkuron commented
A reverted merge will actually revert all changes that happened between the branch and the merge, which is bad. Please do the following after ensuring that you no uncomitted changes:
```
git reset --hard 7bb569a
git push -f
```
This will delete both the merge and its reversal.

2018-08-27 17:39 UTC, mkuron commented
I can retry the merge myself tomorrow. Also, the CRLFs are definitely there in error.

2018-08-27 17:56 UTC, jngrad commented
Interesting, after the reset only the 5 tutorial files we were working on are in conflict, instead of the whole project. Also, the tutorial files have line feed issues too?

2018-08-27 18:56 UTC, jngrad commented
@mkuron I've merged `python` into the proposed PR in a [new branch](https://github.com/jngrad/espresso/compare/pr1...jngrad:pr1-merge) to solve the conflicts, let me know if you still want to retry this merge yourself

2018-08-27 20:32 UTC, mkuron commented
Yes, that new merge looks good. Please push it to this pull request‘s branch. If CI passes, @RudolfWeeber can go ahead and merge.

2018-08-27 20:37 UTC, RudolfWeeber commented
I learned about 
git merge -Xignore-space-change
while having a look.

2018-08-28 09:06 UTC, jngrad commented
running fine

2018-08-28 13:09 UTC, jngrad commented
interesting: if you mix CRLF and LF line feeds in the same file during a merge between a CRLF file and a LF file, the continuous integration command `git --no-pager diff HEAD^ HEAD > style.patch` produces a patch to fix the line feeds, but when you download it, the file is sanitized to LF line feeds, making it useless

2018-08-28 13:54 UTC, merged