WIP: Ci speedup
espressomd/espresso pull request #2206
Opened 2018-08-28 14:46 UTC by RudolfWeeber

* disable compile-time optimizations for builds that don't run the testsuite (gives a factor of 2 on ICP machines with -j2)

* Don't run the full test suite for intel compiler buidls, but keep the mpirun of testsuite/particle.py as it is.

2018-08-28 14:51 UTC, mkuron commented
Please leave the Intel MPI tests there. They actually helped us find bugs before, e.g. when we depended on some undocumented OpenMPI-specific behavior.

2018-08-28 15:07 UTC, mkuron requested changes
Please leave the Intel tests there. They actually helped us find bugs before, e.g. when we depended on some undocumented OpenMPI-specific behavior or some C++ corner case.

2018-08-29 08:20 UTC, hmenke commented on src/core/utils/Span.hpp
> +    return assert(i < size()), m_ptr[i];
Because the form of `assert` is implementation-defined, it is a good idea to disable a possibly overloaded comma operator using
```cpp
return static_cast<void>(assert(i < size())), m_ptr[i];
```

2018-08-29 08:32 UTC, hmenke commented on src/core/utils/Span.hpp
> +    return assert(i < size()), m_ptr[i];
I had a look at the C99 standard and “7.2.1.1 The assert macro” states

> **Returns**
> The `assert` macro returns no value

so you can forget about the above comment.

2018-08-29 09:50 UTC, RudolfWeeber commented
@mkuron

2018-08-29 10:04 UTC, mkuron requested changes

2018-08-29 10:04 UTC, mkuron commented on CMakeLists.txt
> +if (NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
Please add `AND NOT CMAKE_CXX_COMPILER_ID STREQUAL "Intel"`.

2018-08-29 11:59 UTC, fweik commented on .gitlab-ci.yml
> +    - export cmake_params="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG='-g -DNDEBUG'"
Why do you need `-DNDEBUG` if the tests are not run anyway?

2018-08-29 13:41 UTC, fweik commented
I like #2208 better. :-)

2018-08-30 15:40 UTC, closed without merging