Icc stuff
espressomd/espresso pull request #2273
Opened 2018-09-21 07:33 UTC by fweik

Description of changes:
 - Made icc initialization faster
 - Fixed ghost charge synchronization issue
 - Cleanup

2018-09-21 10:07 UTC, fweik commented
Gitlab passed (https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/3518), not sure why it is now showing.

2018-09-21 10:24 UTC, mkuron commented
@fweik, we had a Gitlab outage this morning, so half an hour's worth of pull requests was not mirrored. You have to add another commit if you want to rebuild this pull request. The link you posted is unrelated and for #1924.

2018-09-21 13:46 UTC, KonradBreitsprecher requested changes
Much cleaner. About deactivating ICC, I guess it's ok to leave the ICC charges on their last value, resetting to zero can be easily done on python level.
I'd like to have the ICC_DEBUG stuff in, otherwise it's fine. ICC+ELC needs testing however, see issue #2278.

2018-09-21 13:46 UTC, KonradBreitsprecher commented on src/core/electrostatics_magnetostatics/icc.cpp
>             "decent exception here\n";
Decent enough I guess

2018-09-21 13:46 UTC, KonradBreitsprecher commented on src/core/electrostatics_magnetostatics/icc.cpp
ICC_DEBUG is unused, I suggest to add sth like this here:
```
#ifdef ICC_DEBUG
    fprintf(stderr, "Iteration %d globalmax %f\n", iccp3m_cfg.citeration, globalmax);
#endif
```

2018-09-21 13:46 UTC, KonradBreitsprecher commented on src/core/electrostatics_magnetostatics/icc.cpp
> +
ICC_DEBUG is unused, I suggest to add sth like this here:

```
#ifdef ICC_DEBUG
   fprintf(stderr, "Particle %d q_old %10.5f q_new %10.5f F_n %10.5f E %10.5f %10.5f %10.5f\n", p.p.identity, hold * iccp3m_cfg.areas[id], p.p.q, f1, ex,ey,ez);
#endif
```

2018-09-21 15:12 UTC, KonradBreitsprecher commented on src/core/electrostatics_magnetostatics/icc.cpp
> +        auto const ez = p.f.f[2] / p.p.q + iccp3m_cfg.exty;
Should be ext**z** here.

2018-09-21 15:34 UTC, fweik commented
Good catch.

2018-09-21 15:57 UTC, fweik commented
Do you see any benefit for supporting MMM2D with ICC when you could use ELC instead? It seems to me that ELC supports more boundary conditions and is faster...

2018-09-21 16:21 UTC, KonradBreitsprecher commented
Not really, but if we figured out the validity of 2D methods + ICC, why would you take it out?

2018-09-22 10:30 UTC, fweik commented
Wouldn't it be better to collect proper statistics (maybe on demand) than the debug statements? How do you use this?

2018-09-22 11:44 UTC, KonradBreitsprecher commented
I collect the number of iterations to adjust relaxation parameter and convergence criterion to minimize ICC iterations. This is actually quite essential and should be accessible. The detailed debug statement for all ICC particles with old and new charges etc. is probably not worth interfacing.

2018-09-22 13:51 UTC, fweik commented
Ok I've exposed the number of iterations needed in the last round. Is that sufficient?

2018-09-22 14:20 UTC, KonradBreitsprecher commented
That should do it.

2018-09-22 15:36 UTC, KonradBreitsprecher approved these changes

2018-09-22 16:32 UTC, merged