calc particle dipole vector and director on the fly
espressomd/espresso pull request #2297
Opened 2018-10-10 16:34 UTC by RudolfWeeber

rather than storing them on the particle

The methods are called calc_dip() and calc_quatu() to make it clear that a calculation takes placed when caling them.

This is to reduce particle size and decrease the performance penalty for compiling in rotation and dipoles.

2018-10-10 17:22 UTC, fweik requested changes

2018-10-10 17:22 UTC, fweik commented on src/core/communication.cpp
> +    p->p.dipm = sqrt(p->calc_dip()[0] * p->calc_dip()[0] + p->calc_dip()[1] * p->calc_dip()[1] +
`p->p.dipm = p->calc_dip().norm()`

2018-10-10 17:22 UTC, fweik commented on src/core/electrostatics_magnetostatics/magnetic_non_p3m_methods.cpp
> +double calc_dipole_dipole_ia(Particle *p1, const Vector3d dip1, Particle *p2, int force_flag) {
`const Vector3d & dip1`

2018-10-10 17:22 UTC, fweik commented on src/core/electrostatics_magnetostatics/magnetic_non_p3m_methods.cpp
> +  pe1 = dip1[0] * dip2[0] + dip1[1] * dip2[1] +
`dip1 * dip2`, also next two lines, also init `pe1` here and make const

2018-10-10 17:22 UTC, fweik commented on src/core/electrostatics_magnetostatics/p3m-dipolar.cpp
> +      node_sums[0] += Utils::sqr(dip[0]) + Utils::sqr(dip[1]) +
`node_sums[0] += p.calc_dip().norm2()`

2018-10-10 17:22 UTC, fweik commented on src/core/electrostatics_magnetostatics/p3m-dipolar.hpp
> +  Vector3d dip1=p1->calc_dip();
`const`

2018-10-10 17:22 UTC, fweik commented on src/core/electrostatics_magnetostatics/p3m-dipolar.hpp
> +  Vector3d dip2=p2->calc_dip();
`const`

2018-10-10 17:22 UTC, fweik commented on src/core/electrostatics_magnetostatics/p3m-dipolar.hpp
> +    double mimj = dip1[0] * dip2[0] + dip1[1] * dip2[1] +
`= dip1 * dip2` and next lines

2018-10-10 17:22 UTC, fweik commented on src/core/electrostatics_magnetostatics/p3m-dipolar.hpp
> +  Vector3d dip1=p1->calc_dip();
`const`

2018-10-10 17:22 UTC, fweik commented on src/core/electrostatics_magnetostatics/p3m-dipolar.hpp
> +  Vector3d dip2=p2->calc_dip();
`const`

2018-10-10 17:22 UTC, fweik commented on src/core/forces_inline.hpp
> +      part->f.f[0] += part->swim.f_swim * quatu[0];
`part->f.f += part->swim.f_swim * quatu`

2018-10-10 17:22 UTC, fweik commented on src/core/grid_based_algorithms/lb.cpp
> +    source_position[0] = p->r.p[0] + direction * p->r.calc_quatu()[0];
`auto const source_position = p->r.p + direction * p->r.calc_quatu()`

2018-10-10 17:22 UTC, fweik commented on src/core/particle_data.hpp
> +    return Vector3d({{2 * (quat[1] * quat[3] + quat[0] * quat[2]),
you can leave out the type to reduce clutter. arguably the return type should also be `const`, which makes it clear that this can not be changed like this.

2018-10-10 17:22 UTC, fweik commented on src/core/particle_data.hpp
> +struct pair_ia_lhs_cache {
This seems unused

2018-10-10 17:22 UTC, fweik commented on src/core/rotation.cpp
> +      const Vector3d quatu=p.r.calc_quatu();
`auto const dip = p.swim.dipole_length * p.r.calc_quatu();`

2018-10-10 17:22 UTC, fweik commented on src/core/particle_data.hpp
> +  Vector3d calc_quatu() const {
This should get be a better name than than `calc_quatu` like `calc_director` or `calc_orientation` or similar. Also this could be a free function.

2018-10-14 21:36 UTC, RudolfWeeber commented
> fweik requested changes on this pull request.
> 
> 
> 
> > @@ -892,16 +884,9 @@ void mpi_send_dip(int pnode, int part, double dip[3]) {
>  
>    if (pnode == this_node) {
>      Particle *p = local_particles[part];
> -    p->r.dip[0] = dip[0];
> -    p->r.dip[1] = dip[1];
> -    p->r.dip[2] = dip[2];
> -#ifdef ROTATION
> -    convert_dip_to_quat(p->r.dip, p->r.quat, &p->p.dipm);
> -    convert_quat_to_quatu(p->r.quat, p->r.quatu);
> -#else
> -    p->p.dipm = sqrt(p->r.dip[0] * p->r.dip[0] + p->r.dip[1] * p->r.dip[1] +
> -                     p->r.dip[2] * p->r.dip[2]);
> -#endif
> +    convert_d ip_to_quat(Vector3d({dip[0],dip[1],dip[2]}), p->r.quat, &p->p.dipm);
> +    p->p.dipm = sqrt(p->calc_dip()[0] * p->calc_dip()[0] + p->calc_dip()[1] * p->calc_dip()[1] +
> 
> `p->p.dipm = p->calc_dip().norm()`
Turns out the first call (dip_to_quat) sets the scalar moment.

Rest is done, I think.

2018-10-14 21:40 UTC, fweik approved these changes

2018-10-14 21:41 UTC, fweik commented
Ok thank you. I think `director` is a considerable improvement over `quatu` ^^.

2018-10-15 15:19 UTC, merged