Update particles.rst
espressomd/espresso pull request #2355
Opened 2018-10-31 07:37 UTC by jonaslandsgesell

Important information on how many particles are actually set. It was ambiguous whether node particles are included in the counter or not. Like this the documentation is complete and unambiguous.

Fixes #

Description of changes:
 - 

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2018-10-31 10:40 UTC, RudolfWeeber commented
Please re-check the grammar. I don't understand the new sentence. What is the origin of the +8?

2018-10-31 11:08 UTC, jonaslandsgesell commented
It is the 8 nodes which are added

Am Mi., 31. Okt. 2018, 11:40 hat RudolfWeeber <notifications@github.com>
geschrieben:

> Please re-check the grammar. I don't understand the new sentence. What is
> the origin of the +8?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/pull/2355#issuecomment-434639939>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE8wPcJua8_DYiqsjJolEpGjZm_M3i__ks5uqX4tgaJpZM4YDgk9>
> .
>

2018-11-03 05:18 UTC, KaiSzuttor requested changes

2018-11-03 05:18 UTC, KaiSzuttor commented on doc/sphinx/particles.rst
> +See :meth:`espressomd.diamond.Diamond` for more details. For simulating compressed or streched gels the function
typo stretched

2019-02-01 08:40 UTC, KaiSzuttor approved these changes

2019-02-01 11:03 UTC, merged