Lb philox rng particle
espressomd/espresso pull request #2363
Opened 2018-11-02 20:16 UTC by KaiSzuttor

Follow up on #2348 

Description of changes:
 - remove old self-written RNG for particle thermalization in LB GPU

2018-11-03 14:01 UTC, fweik commented
Sorry I did not catch this before. But 32 bit for the state seems a little bit short for me (this is also the period obviously), if you could easily use 64 bit please do so.

Also since you removed the checkpointing code for seed, how is the state checkpointed?

2018-11-03 14:42 UTC, mkuron requested changes

2018-11-03 14:42 UTC, mkuron commented on src/core/grid_based_algorithms/lbgpu_cuda.cu
> +        random_wrapper_philox(part_index, ii, philox_counter);
Right now this generates the same random numbers as for some fluid cells. You should replace `ii` with `ii + 1024` or something.

2018-11-03 14:45 UTC, mkuron commented
> But 32 bit for the state seems a little bit short for me (this is also the period obviously)

It's the period per particle, so it is sufficient. Each particle gets a completely different series of 2^32 numbers.

> Also since you removed the checkpointing code for seed, how is the state checkpointed?

That's why I said it should just use the time step number. Though I actually don't know if that is even checkpointed.

2018-11-03 15:08 UTC, fweik commented
2^32 isn't so big, and I can see no reason to leave just half of the state unused.

2018-11-03 16:06 UTC, mkuron commented
Of course we could use more bits as state, but it's probably not needed. Right now we can have 4 billion time steps times 4 billion seeds before it repeats. But we imply that you have less than 4 billion particles.

2018-11-03 16:15 UTC, fweik commented
From my understanding it's not `times`, after the overflow everything will repeat, or do I misunderstand something?

2018-11-03 16:18 UTC, fweik commented
It's used like
```c++
    float4 random_floats =
random_wrapper_philox(part_index, ii, philox_counter);
```
`part_index` and `ii` are fixed, so if `philox_counter` overflows, everything repeats.

2018-11-03 16:19 UTC, fweik commented
More correctly, the distribution of `part_index` is unknown, it's maybe even not such a great choice.

2018-11-03 17:16 UTC, mkuron commented
`part_index` is the ID of the particle, so you get independent series of random numbers for each particle (as long as you have less than 4 billion of them). `philox_counter` overflows once every 4 billion time steps, so the series for each particle repeats after 4 billion time steps. `ii` is indeed fixed. The distribution of `part_index` does not matter because a hash function produces a random distribution from anything.

2018-11-03 17:20 UTC, fweik commented
`part_index` is not the id.

2018-11-03 17:34 UTC, mkuron commented
What else is it? It looks like it is the particle ID, and @KaiSzuttor probably used it because he thought that too.

2018-11-03 17:44 UTC, fweik commented
It's not, the id is not known on the device. Its some random index depending on the order of the particles in the cells and nodes.

2018-11-03 19:18 UTC, KaiSzuttor commented
urgh maybe we think about changing the particle thermalization coupling is done on the cpu. its currently also not clear to me how we would achieve normal distribution with the “stateless” philox

2018-11-03 19:19 UTC, KaiSzuttor commented
yes, checkpointing is broken

2018-11-03 21:42 UTC, mkuron commented
> Its some random index depending on the order of the particles in the cells and nodes

As long as the tuple (`part_index`, `philox_counter`) is unique, we are good. And for that the order of the particles doesn’t matter as long as `part_index` is unique within a single time step.

2018-11-04 12:37 UTC, fweik commented
I don't like the `particle_index`, we can just copy the id to the device.

2018-11-04 13:05 UTC, mkuron commented
You are probably right. Even though it is unique, if it depends on some sort order, it's probably not deterministic. So rerunning with the same seed may produce different results.

2018-11-06 15:59 UTC, fweik requested changes
The counter is still 32 bit.

2018-11-07 08:07 UTC, KaiSzuttor commented
@fweik, I'm not sure what you mean. The curand function expects uint.

2018-11-07 08:53 UTC, mkuron approved these changes

2018-11-07 09:02 UTC, mkuron commented
I think @fweik means that `philox_counter` rolls over after 4 billion time steps. This most likely isn't going to be a common thing to happen: even if your simulation is running at 1000 time steps per second, it would have to run for 7 weeks before the counter rolls over.

The curand function takes 4x32 bits as counter and 2x32 bits as key. Right now we use the cell index or particle ID, two zeros, and the mode number or 32 as _counter_ and `philox_counter` and the seed as _key_. To roll over beyond 4 billion time steps, we could use a 64-bit `philox_counter` as _key_ (just reinterpret it as a `uint2`) and replace one of the zeros in _counter_ with the seed.

2018-11-07 09:05 UTC, KaiSzuttor commented
@mkuron, I was faster :haha:

2018-11-07 12:38 UTC, KaiSzuttor commented
@fweik

2018-11-07 14:45 UTC, fweik approved these changes

2018-11-07 14:46 UTC, merged