WIP: Rotation cleanup
espressomd/espresso pull request #2382
Opened 2018-11-22 19:02 UTC by RudolfWeeber

* Remove duplicated frame conversion code
* Make use of Vector3d

2018-11-23 21:46 UTC, RudolfWeeber commented
Fixes #2383.

The engine tests only check against a stored reference file.
I checked that the engine_lb test passes, if I re-introduce the sign error.
This PR replaced the reference data with data generated with the correct cross product. @hmanke @jdgraaf

2018-11-24 06:17 UTC, KaiSzuttor submitted a review, later dismissed

2018-11-24 06:17 UTC, KaiSzuttor commented on src/core/communication.cpp
> +void mpi_send_omega(int pnode, int part, const double omega[3]) {
const Vector3d& omega

2018-11-24 06:17 UTC, KaiSzuttor commented on src/core/communication.cpp
> +void mpi_send_torque(int pnode, int part, const double torque[3]) {
const Vector3d& torque

2018-11-24 06:17 UTC, KaiSzuttor commented on src/core/rotation.cpp
> +    convert_torque_to_body_frame_apply_fix_and_thermostat(Particle &p) {
if there is an “and” in the function name you should think about splitting it

2018-11-24 13:55 UTC, fweik requested changes

2018-11-24 13:55 UTC, fweik commented on src/core/communication.cpp
> +    MPI_Send(axis.data(), 3, MPI_DOUBLE, pnode, SOME_TAG, comm_cart);
Please use boost::mpi, which will also fix all the builds.

2018-11-24 13:55 UTC, fweik commented on src/core/communication.cpp
> +    MPI_Recv(axis.data(), 3, MPI_DOUBLE, 0, SOME_TAG, comm_cart,
boost::mpi

2018-11-24 13:55 UTC, fweik commented on src/core/minimize_energy.cpp
> +    Vector3d dq; // Vector parallel to torque
Looks like can directly initialize `dq` and remove the loop in line 100.

2018-11-24 13:55 UTC, fweik commented on src/core/rotation.cpp
> +
remove empty line

2018-11-24 13:55 UTC, fweik commented on src/core/rotation.cpp
> +void local_rotate_particle(Particle &p, const Vector3d &a_space_frame,
Please rename `a_space_frame` to `axis`.

2018-11-26 15:03 UTC, RudolfWeeber commented
Fixes #1318

2018-11-26 15:05 UTC, fweik approved these changes

2018-11-30 19:22 UTC, merged