CMake: Default with_scafacos = off, since it requries ELECTROSTATICS
espressomd/espresso pull request #2417
Opened 2018-12-14 14:54 UTC by RudolfWeeber

@fweik

2018-12-14 16:52 UTC, fweik approved these changes

2019-01-07 07:51 UTC, fweik requested changes

2019-01-07 07:51 UTC, fweik commented on maintainer/CI/build_cmake.sh
> +cmake_params="-DCMAKE_BUILD_TYPE=$build_type -DPYTHON_EXECUTABLE=$(which python$python_version) -DWARNINGS_ARE_ERRORS=ON -DTEST_NP:INT=$check_procs $cmake_params -DWITH_SCAFACOS=ON"
I don't think you can do `-DWITH_SCAFACOS=ON` in the build script for all builds as there are containers where there is now scafacos; on these the build should fail now.

2019-01-07 08:35 UTC, RudolfWeeber commented
On Sun, Jan 06, 2019 at 11:51:26PM -0800, Florian Weik wrote:
> fweik requested changes on this pull request.
> 
> 
> 
> > @@ -84,7 +84,7 @@ if [[ ! -z ${with_coverage+x} ]]; then
>    bash <(curl -s https://codecov.io/env) &> /dev/null;
>  fi
>  
> -cmake_params="-DCMAKE_BUILD_TYPE=$build_type -DPYTHON_EXECUTABLE=$(which python$python_version) -DWARNINGS_ARE_ERRORS=ON -DTEST_NP:INT=$check_procs $cmake_params"
> +cmake_params="-DCMAKE_BUILD_TYPE=$build_type -DPYTHON_EXECUTABLE=$(which python$python_version) -DWARNINGS_ARE_ERRORS=ON -DTEST_NP:INT=$check_procs $cmake_params -DWITH_SCAFACOS=ON"
> 
> I don't think you can do `-DWITH_SCAFACOS=ON` in the build script for all builds as there are containers where there is now scafacos; on these the build should fail now.
Just like WITH_CUDA, the switch enables the detection, not the
actual use.

2019-01-07 08:39 UTC, fweik approved these changes

2019-01-07 08:40 UTC, fweik commented
Find with me, the main point was to avoid the build failures.

2019-01-07 17:07 UTC, merged