Speedup back assignment of forces/torques from gpu methods
espressomd/espresso pull request #2446
Opened 2019-01-16 18:10 UTC by RudolfWeeber

By not using cuda pinned memory. 
In lj+lb fluids with n=1000, phi=0.1, agrid=sigma, this increases performance by a third.

2019-01-16 18:16 UTC, fweik requested changes

2019-01-16 18:16 UTC, fweik commented on src/core/cuda_common_cuda.cu
> +      particle_forces_host = (float *)malloc(
Please don't use c-style casts. Don't use raw pointers. Don't use malloc.

2019-01-16 18:16 UTC, fweik commented on src/core/cuda_common_cuda.cu
> +      host_v_cs = (float *)malloc(global_part_vars_host.number_of_particles *
Please don't use c-style casts. Don't use raw pointers. Don't use malloc.

2019-01-16 18:16 UTC, fweik commented on src/core/cuda_common_cuda.cu
> +      particle_torques_host = (float *)malloc(
Please don't use c-style casts. Don't use raw pointers. Don't use malloc.

2019-01-16 19:16 UTC, mkuron requested changes
Please use `free` with these variables (around line 240) instead of the previous `cudaFreeHost`.

2019-01-16 19:16 UTC, mkuron commented
Do you why these special allocations were previously used? If `cudaHostAllocDefault` or `cudaHostAllocMapped` were used, it could be used with `cudaMemcpyAsync`, but that's not the case here. The documentation says
> `cudaHostAllocWriteCombined`: Allocates the memory as write-combined (WC). WC memory can be transferred across the PCI Express bus more quickly on some system configurations, but cannot be read efficiently by most CPUs. WC memory is a good option for buffers that will be written by the CPU and read by the device via mapped pinned memory or host->device transfers.

So since these variables are used for copying data from the GPU to the CPU and then reading that data on the CPU, that option is clearly inappropriate.

2019-01-16 19:20 UTC, mkuron commented
There are two more instances of `cudaHostAlloc` in this file. The one for `fluid_composition_host` looks like it's the same situation as the one you fixed for the other three variables, while the one for `particle_data_host` should probably use `cudaHostAllocWriteCombined|cudaHostAllocMapped` (right now the memory isn't pinned and the `cudaMemcpyAsync` will be synchronous).

2019-01-16 23:11 UTC, RudolfWeeber commented
On Wed, Jan 16, 2019 at 11:20:12AM -0800, Michael Kuron wrote:
> There are two more instances of `cudaHostAlloc` in this file. The one for `fluid_composition_host` looks like it's the same situation as the one you fixed for the other three variables, while the one for `particle_data_host` should probably use `cudaHostAllocWriteCombined|cudaHostAllocMapped` (right now the memory isn't pinned and the `cudaMemcpyAsync` will be synchronous).
I'm not going to touch the ShanChen stuff because it has not tests
the device, so it probably should stay the way it is.

I matched the frees and changed the malloc type. No difference in
timing (within 5%)

For 10k particles, the difference between non-lb an lb is 4 vs 4.7ms
/ time step.
Of the 0.7ms the leading (host-blocking) gpu operation is 0.2 ms for
the blocking transfer of the forces from the gpu to the host.

2019-01-17 07:56 UTC, fweik commented
If think what @mkuron wante to say that you have to use `free` with `malloc` and `cudaFree` with `cudaMalloc`. Otherwise you are assuming cuda uses malloc to allocate memory.

2019-01-17 08:04 UTC, RudolfWeeber commented
On Wed, Jan 16, 2019 at 11:56:27PM -0800, Florian Weik wrote:
> If think what @mkuron wante to say that you have to use `free` with `malloc` and `cudaFree` with `cudaMalloc`. Otherwise you are assuming cuda uses malloc to allocate memory.
I think I did that.

2019-01-17 08:16 UTC, fweik commented
As sorry I misread. Why can't use just use a vector? I not going to merge it like this.

2019-01-17 08:21 UTC, mkuron requested changes

2019-01-17 08:21 UTC, mkuron commented on src/core/cuda_common_cuda.cu
> +                        cudaHostAllocWriteCombined ));
This should use `cudaHostAllocWriteCombined|cudaHostAllocMapped`. Otherwise the memory copy isn't actually going to be asynchronous.

2019-01-17 09:19 UTC, RudolfWeeber commented
On Thu, Jan 17, 2019 at 12:21:51AM -0800, Michael Kuron wrote:
> mkuron requested changes on this pull request.
> 
> 
> 
> > @@ -262,26 +262,21 @@ void gpu_change_number_of_part_to_comm() {
>      if (global_part_vars_host.number_of_particles) {
>  
>        /**pinned memory mode - use special function to get OS-pinned memory*/
> -      cuda_safe_mem(cudaHostAlloc((void **)&particle_data_host,
> -                                  global_part_vars_host.number_of_particles *
> -                                      sizeof(CUDA_particle_data),
> -                                  cudaHostAllocWriteCombined));
> -      cuda_safe_mem(cudaHostAlloc(
> -          (void **)&particle_forces_host,
> -          3 * global_part_vars_host.number_of_particles * sizeof(float),
> -          cudaHostAllocWriteCombined));
> +      cuda_safe_mem(
> +          cudaHostAlloc((void **)&particle_data_host,
> +                        global_part_vars_host.number_of_particles *
> +                            sizeof(CUDA_particle_data),
> +                        cudaHostAllocWriteCombined ));
> 
> This should use `cudaHostAllocWriteCombined|cudaHostAllocMapped`. Otherwise the memory copy isn't actually going to be asynchronous.
I read the docs differently. Mapped memory can be accessed directly
from the gpu without an explicit copy. It is however not supported
on HIP. Adding the flag also does not impact performance.
I also tried adding cudaHostAllocPortable which also explicitly
mentions "pinned". Also no impact.
I think, the docs are unclear.

Furthermore, the profile (from nvprof) suggests that the transfer is
quite efficient (if not actually asynchroneous):
      API calls:   
33.26%  258.92ms      5006  51.722us  cudaMemcpy (back transfer device->host)
30.51%  237.48ms     15010  15.821us  cudaLaunch
13.38%  104.15ms         1  104.15ms  cudaStreamCreate
12.78%  99.460ms      5002  19.883us  cudaMemcpyAsync (particle data
host->gpu)

So, a third of the time for 3x the amount of data (3pos, 3v, 1id vs
3force).

Further performance work has to go to the back transfer of the
forces, I think.
For example, the transfer of torques (for builds with rotation) can
be ommitted if no gpu method actually uses them.

2019-01-17 10:47 UTC, RudolfWeeber commented
On Thu, Jan 17, 2019 at 12:16:14AM -0800, Florian Weik wrote:
> As sorry I misread. Why can't use just use a vector? I not going to merge it like this.
It's part of the pr now. I still find that an unrelated task,
though.

2019-01-17 10:55 UTC, fweik approved these changes

2019-01-17 10:55 UTC, fweik commented on src/core/cuda_interface.hpp
> +                        std::vector<CUDA_v_cs> host_v_cs);
This should probably be a reference

2019-01-21 22:17 UTC, merged