ElectricPlaneWave external field
espressomd/espresso pull request #2496
Opened 2019-02-04 18:00 UTC by fweik

This ads electric plane fields as constraints.

PR Checklist
------------
 - [x] Tests?
   - [x] Interface
   - [ ] Core 
 - [x] Docs?

2019-02-04 21:23 UTC, jonaslandsgesell commented on src/python/espressomd/constraints.py
> +
What is the direction of the electric field? E0 is only the amplitude as described below (i.e. a scalar value). The electric field and the wave vector do not need to coincide if there are charge densities.

2019-02-04 21:26 UTC, fweik commented on src/python/espressomd/constraints.py
> +
`E0` is a vector

2019-02-05 09:51 UTC, jonaslandsgesell commented on testsuite/python/field_test.py
> +
Could you please also test the propagation of the Electric wave please (maybe for a fixed particle)?
Otherwise this looks fine to me

2019-02-06 09:00 UTC, KaiSzuttor requested changes

2019-02-06 09:00 UTC, KaiSzuttor commented on src/core/constraints/Constraints.hpp
> +  void add_forces(ParticleRange &particles, double t) const {
Could you please add documentation for the parameters, especially for the newly introduced ``t``?

2019-02-06 09:00 UTC, KaiSzuttor commented on src/core/field_coupling/fields/PlaneWave.hpp
> +  PlaneWave(const value_type amplitude, const value_type &k, T omega, T phase)
please add documentation for the new class

2019-02-07 15:28 UTC, fweik commented
@KaiSzuttor

2019-02-08 14:42 UTC, KaiSzuttor approved these changes

2019-02-08 14:53 UTC, merged