testsuite: Test both interpolaton code paths of p3m
espressomd/espresso pull request #2662
Opened 2019-04-04 15:53 UTC by fweik

P3M can optionally use an interpolated window function, this tests both possible code paths.

2019-04-09 13:44 UTC, KaiSzuttor commented on testsuite/python/coulomb_cloud_wall.py
> +        def test_p3m_direct_caf(self):
please add a docstring

2019-04-09 16:16 UTC, fweik commented on testsuite/python/coulomb_cloud_wall.py
> +        def test_p3m_direct_caf(self):
They all run the same check with different methods, none of the other test functions have docstrings.

2019-04-09 17:19 UTC, KaiSzuttor commented on testsuite/python/coulomb_cloud_wall.py
> +        def test_p3m_direct_caf(self):
while I can imagine what happens in ```test_scafacos_p3m``` its hard to grasp the meaning of ```test_p3m_direct_caf```

2019-04-11 08:03 UTC, KaiSzuttor requested changes
once the tests have a short description it can be merged

2019-04-11 10:28 UTC, KaiSzuttor submitted a review, later dismissed

2019-04-11 10:28 UTC, KaiSzuttor commented
bors r+

2019-04-11 15:48 UTC, KaiSzuttor commented
bors r+

2019-04-11 21:09 UTC, KaiSzuttor commented
bors r+

2019-04-11 21:10 UTC, KaiSzuttor approved these changes

2019-04-11 22:56 UTC, merged