Mpiio test
espressomd/espresso pull request #2703
Opened 2019-04-10 15:59 UTC by hirschsn

Fixes missing MPI-IO test (see #2071).

Description of changes:
 - Add a test that creates random particles, dumps them, reads them in, again and verifies the read particles.

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2019-04-11 09:07 UTC, hirschsn commented
Oops, some of the test pipelines fail. I'll look into it. :)

2019-04-11 14:30 UTC, hirschsn commented
Should be good now.

2019-04-11 19:13 UTC, fweik submitted a review, later dismissed

2019-04-11 19:14 UTC, KaiSzuttor requested changes
thanks for your effort! could you please address my comments

2019-04-11 19:14 UTC, KaiSzuttor commented on testsuite/python/mpiio.py
> +    def setup_sample_system(self):
could you please use the python unittest class' special functions like ```setUp``` etc. for preparing and cleanup?

2019-04-11 19:14 UTC, KaiSzuttor commented on testsuite/python/mpiio.py
> +    def assertAllEqual(self, v, w):
please check if the numpy testing module provides this functionality

2019-04-15 09:18 UTC, hirschsn commented
@KaiSzuttor, thanks for the comments, done.

2019-04-15 11:41 UTC, KaiSzuttor approved these changes

2019-04-15 11:41 UTC, KaiSzuttor commented
thanks steffen

2019-04-15 11:41 UTC, KaiSzuttor commented
bors r+

2019-04-15 12:53 UTC, merged