WIP: Hacky support for gdb in ipypresso
espressomd/espresso pull request #2781
Opened 2019-04-30 13:12 UTC by hirschsn

Ipypresso's flag "--gdb" does not work on my system because ipypresso is just a wrapper script executing python with a bunch of parameters. Nevertheless, support of --gdb can be added to ipypresso by a slightly more complicated gdb setup.

This PR adds this support using gdb's exec-wrapper functionality. The implementation is quite hacky by inserting a check for ipython into pypresso.cmakein. Let me know if the functionality itself is something that you want to have upstream. If so, we also could figure out a less hacky solution.

Description of changes:
 - Use ipython as gdb's exec-wrapper, not directly as executable

PR Checklist
------------
 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2019-05-02 06:56 UTC, KaiSzuttor commented
@mkuron could you please have a look?

2019-05-09 05:39 UTC, KaiSzuttor commented
@mkuron

2019-05-09 07:24 UTC, mkuron requested changes
Paths shouldn't be hardcoded. Use the respective CMake variables.

2019-05-09 09:57 UTC, hirschsn commented
@mkuron You're right. Is there a possibility to get the path of the python executable from cmake if the frontend is ipython?

2019-05-09 10:34 UTC, mkuron commented
There are `IPYTHON_EXECUTABLE` and `PYTHON_EXECUTABLE`.

2019-05-09 13:43 UTC, jngrad commented
Here's a MWE to reproduce the bug:
```
./ipypresso --gdb script.py
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
"/usr/bin/ipython": not in executable format: File format not recognized
(gdb) run
Starting program:  script.py
No executable file specified.
Use the "file" or "exec-file" command.
```
And the result after this PR:
```
./ipypresso --gdb script.py   # assuming script.py fails
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Reading symbols from /usr/bin/python2...Reading symbols from /usr/lib/debug/.build-id/fd/3904306c73383fb371287416257b82d6a3363b.debug...done.
done.
(gdb) run
Starting program: /usr/bin/python2 script.py

process 3301854 is executing new program: /usr/bin/python2.7
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Inferior 1 (process 3301854) exited normally]
```
which is the expected behavior: ipypresso should give the same output as pypresso.

The regex is not necessary and won't work here because there is no guarantee the IPython program is called "ipython". We already support Jupyter as a fallback when IPython is not found, and users are free to override that choice with `cmake -DIPYTHON_EXECUTABLE=~/coding/my-own-ipynb-interpreter/bin ..`

You can simply do the following:
```cmake
    --gdb)
        shift
        [ "@PYTHON_FRONTEND@" = "@IPYTHON_EXECUTABLE@" ] && exec gdb -ex "set print thread-events off" -ex "set exec-wrapper sh -c 'exec @IPYTHON_EXECUTABLE@ \"$@\"'" --args "@PYTHON_EXECUTABLE@" $@
        exec gdb --args @PYTHON_FRONTEND@ $@
```

2019-05-09 15:19 UTC, hirschsn commented
@jngrad  Thanks for your suggestion, that's right. Changed it.

2019-05-09 17:11 UTC, jngrad commented
With 556501f there is a difference in behavior for ipypresso:
`./ipypresso --gdb` then `(gdb) run script.py`: starts ipython prompt without executing the script
`./ipypresso --gdb script.py` then `(gdb) run`: does not start ipython prompt but executes the script
Probably not related to the changes in this PR: `./pypresso --gdb` sometimes spans multiple threads.

2019-05-14 09:06 UTC, hirschsn commented
@jngrad thanks, again, for your thoroughness. Accidentally, the $@ was evaluated too early. Now the sh of the exec-wrapper evaluates it and arguments to run should work.

2019-05-14 12:09 UTC, jngrad approved these changes

2019-05-14 17:55 UTC, jngrad commented
bors r+

2019-05-14 19:16 UTC, merged