Mindist
espressomd/espresso pull request #2817
Opened 2019-05-08 13:21 UTC by fweik

Follow up on #2816.

2019-05-08 14:00 UTC, jngrad requested changes
add the new python test to CMakeLists.txt

2019-05-08 14:08 UTC, hirschsn commented
Oops, my bad, sorry. :)

2019-05-08 14:17 UTC, pkreissl commented on testsuite/python/analyze_distance_empty.py
> +        self.assertEqual(self.system.analysis.min_dist(), float("inf"))
`numpy.inf`

2019-05-08 14:31 UTC, jngrad commented on testsuite/python/CMakeLists.txt
> +python_test(FILE analyze_distance_empty.py MAX_NUM_PROC 256)
`MAX_NUM_PROC` should be 1 (just like analyze_distance.py) because the function being tested is not likely to break when more CPU cores are used

2019-05-09 09:50 UTC, fweik commented
@jngrad

2019-05-09 09:52 UTC, jngrad approved these changes

2019-05-09 09:53 UTC, fweik commented
bors r+

2019-05-09 12:11 UTC, merged