LB observable
espressomd/espresso pull request #2818
Opened 2019-05-08 14:10 UTC by KaiSzuttor

2019-05-10 11:35 UTC, fweik requested changes

2019-05-10 11:35 UTC, fweik commented on src/core/observables/LBProfileObservable.hpp
> +  std::vector<double> m_sample_positions;
Shouldn't this be a `Vector3d` or similar?

2019-05-10 11:35 UTC, fweik commented on src/utils/include/utils/coordinate_transformation.hpp
> +inline Vector3d transform_velocity_cartesian_to_cylinder(
Why is there a special transform for velocities?

2019-05-10 11:35 UTC, fweik commented on src/utils/include/utils/Vector.hpp
> +std::ostream &operator<<(std::ostream &out, Vector<T, N> const &a) {
This
- adds an extra space at the end
- is not tested
- is not templated on the outstream.

2019-05-10 11:35 UTC, fweik commented on src/utils/include/utils/sampling.hpp
> +  auto n_phi_samples = [arc_length](int r_bin) {
So `n_phi_samples(i) = i + 1` ? You can actually make this a function of r instead of the count, then you don't need the iterators later.

2019-05-10 11:44 UTC, KaiSzuttor commented on src/core/observables/LBProfileObservable.hpp
> +  std::vector<double> m_sample_positions;
Maybe, it's not part of the changes for this PR

2019-05-10 11:44 UTC, KaiSzuttor commented on src/utils/include/utils/coordinate_transformation.hpp
> +inline Vector3d transform_velocity_cartesian_to_cylinder(
Because you need to transform the velocities into cylinder coordinates

2019-05-10 11:44 UTC, KaiSzuttor commented on src/utils/include/utils/Vector.hpp
> +std::ostream &operator<<(std::ostream &out, Vector<T, N> const &a) {
I can remove it...

2019-05-10 11:46 UTC, fweik commented on src/utils/include/utils/coordinate_transformation.hpp
> +inline Vector3d transform_velocity_cartesian_to_cylinder(
The function should be called `transform_cartesian_to_cylinder` right?

2019-05-10 11:54 UTC, KaiSzuttor commented on src/utils/include/utils/coordinate_transformation.hpp
> +inline Vector3d transform_velocity_cartesian_to_cylinder(
and how do I distinguish from the function for coordinates?

2019-05-10 17:55 UTC, fweik commented on src/utils/include/utils/coordinate_transformation.hpp
> +inline Vector3d transform_velocity_cartesian_to_cylinder(
Is that a different transformation?

2019-05-13 08:18 UTC, KaiSzuttor commented on src/utils/include/utils/coordinate_transformation.hpp
> +inline Vector3d transform_velocity_cartesian_to_cylinder(
yes

2019-05-13 09:28 UTC, fweik commented
Can you please also look at the change in the class hierarchy from #2830, and see that this is compatible?

2019-05-13 09:30 UTC, fweik commented on src/core/observables/LBProfileObservable.hpp
> +  std::vector<double> m_sample_positions;
Still, though...

2019-05-13 10:28 UTC, KaiSzuttor commented
should not be a problem...

2019-05-13 12:12 UTC, KaiSzuttor commented on src/core/observables/LBProfileObservable.hpp
> +  std::vector<double> m_sample_positions;
I did it, just for you... :+1:

2019-05-13 12:16 UTC, KaiSzuttor commented on src/utils/include/utils/sampling.hpp
> +  auto n_phi_samples = [arc_length](int r_bin) {
i find it more readable as it is now

2019-05-13 19:17 UTC, KaiSzuttor commented
@fweik could you please have a look at the failing accumulator test? It seems related to the script interface.

2019-05-14 08:19 UTC, KaiSzuttor commented
@fweik maybe it's easier for you to merge this

2019-05-14 14:57 UTC, fweik commented
Inheritance from `ProfileObservable` has little benefit, but does greatly increase the complexity. You should solve that differently.

2019-05-14 18:42 UTC, fweik commented
There wasn't anything wrong with your code: There was a latent bug in the python code that was triggered by your changes because you introduced a class that is not default constructible.

2019-05-14 20:40 UTC, KaiSzuttor commented
Why did the build of ```make_lin_range``` not fail in the already merged PR? Are the utils plus test actually build and run in the CI? It seems like the build issue on redhat only now pops up because I use the function... So ```make_lin_range``` is not compatible with boost 1.53.0 at least.

2019-05-14 21:17 UTC, fweik commented
Good question, but they are run somewhere, see https://github.com/espressomd/espresso/issues/2825

2019-05-15 05:20 UTC, KaiSzuttor commented
Ah no checks ror centos 7

> Am 14.05.2019 um 23:17 schrieb Florian Weik <notifications@github.com>:
> 
> Good question, but they are run somewhere, see #2825
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-05-15 07:17 UTC, mkuron commented
@espresso-ci, have you become self-aware?

2019-05-15 07:51 UTC, KaiSzuttor commented
I just pressed the response button, an whoops I became espresso-ci

2019-05-15 07:51 UTC, fweik commented
That's actually how a lot of AI works ^^

2019-05-31 11:26 UTC, KaiSzuttor commented
```-G``` disables all optimization for device code

2019-06-05 07:04 UTC, fweik commented
@KaiSzuttor please fix the sphinx error, than this is good to go.

2019-06-05 08:39 UTC, KaiSzuttor commented
the sphinx error is not specific to this PR but is rather connected to an update of sphinx in the container

2019-06-06 11:12 UTC, KaiSzuttor commented
@fweik

2019-06-06 11:14 UTC, fweik commented
bors r+

2019-06-06 11:30 UTC, KaiSzuttor commented
i think you have to approve

2019-06-06 11:31 UTC, fweik approved these changes

2019-06-06 12:11 UTC, merged