maintainer: add a job with the minimum required boost version
espressomd/espresso pull request #2849
Opened 2019-05-20 14:17 UTC by KaiSzuttor

Fixes #2837

2019-05-22 08:14 UTC, KaiSzuttor commented
this needs to be merged before we can test the new container in the docker PR. After that we can activate the job in the CI.

2019-05-22 08:45 UTC, KaiSzuttor commented
@fweik any idea, what is happening there?
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/116554

2019-05-22 09:01 UTC, mkuron commented
> https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/116554
> mpiexec noticed that process rank 1 with PID 0 on node coyote exited on signal 4 (Illegal instruction).

That also happened last night in the i386 container: https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/116520 (#2851). Sounds like the compiler is generating instructions not supported by the processor?

2019-05-22 09:35 UTC, KaiSzuttor commented
@jngrad I don't understand the failing samples test. If I locally run the sample ```observables_correlators.py``` I get the exact same error for the current python branch. However, the CI did only detect the issue in this PR. Could you please have a look into that?

2019-05-22 10:08 UTC, jngrad commented
@KaiSzuttor found it: `Accumulators::Correlator::set_correlation_args()` in the core is never called by the interface constructor `ScriptInterface::Accumulators::Correlator::Correlator()`, so the value `[10, 10, 10]` passed to argument `args` are not copied to `m_correlation_args`, which is left uninitialized, usually with values `[0., 0., 0.]`, so no throw (and returns wrong numerical results).
https://github.com/espressomd/espresso/blob/0520af905d8914c284b672e9c0493414a063c66b/src/script_interface/accumulators/Correlator.hpp#L43-L53

2019-05-22 10:18 UTC, KaiSzuttor commented
But why is this not an issue in the current python branch?

> Am 22.05.2019 um 12:08 schrieb Jean-Noël Grad <notifications@github.com>:
> 
> @KaiSzuttor found it: Accumulators::Correlator::set_correlation_args() in the core is never called by the interface constructor ScriptInterface::Accumulators::Correlator::Correlator(), so the value [10, 10, 10] passed to argument args are not copied to m_correlation_args, which is left uninitialized, usually with values [0., 0., 0.], so no throw (and returns wrong numerical results).
> https://github.com/espressomd/espresso/blob/0520af905d8914c284b672e9c0493414a063c66b/src/script_interface/accumulators/Correlator.hpp#L43-L53
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-05-22 10:51 UTC, fweik requested changes

2019-05-22 10:51 UTC, fweik commented on src/core/io/writer/h5md_core.hpp
> +#include "communication.hpp"
Please clean up the header. I think the core headers are only needed in the implementation..

2019-05-22 11:54 UTC, jngrad commented
The scenario `corr_operation="fcs_acf"` is untested, so only jobs with sample checks enabled will run it via the sample `observables_correlators.py`. When printing the member `correlation_args`, I get either `0.000000 0.000000 0.000000` or `0.000000 0.000000 -7732675196468477331125564344973318597912019529669651378575435354452340506624.000000` followed by our RuntimeError.  `T m_data[N];` (the internal data structure for `Vector3d correlation_args`) should be implicitly zero-initialized, so there must be an issue with pointers. From my side the RuntimeError frequency is rather low and very sensitive to how many print/printf functions I add in the core class or in the sample script.

2019-05-22 12:21 UTC, fweik submitted a review, later dismissed

2019-05-22 12:42 UTC, fweik commented
The correlator code is unreadable and incomprehensible, I don't think it is worth while investigating any issues in it.

2019-05-22 12:52 UTC, fweik commented
@jngrad you wrote
> Accumulators::Correlator::set_correlation_args() in the core is never called by the interface constructor ScriptInterface::Accumulators::Correlator::Correlator()

The constructor of `ScriptInterface::Accumulators::Correlator::Correlator()` is not where the contained object is initialized, but by the call of `make_shared` in `ScriptInterface::Accumulators::Correlator::construct`...

2019-05-22 12:55 UTC, jngrad commented
Yes I realized it after posting my message. There is no `args` argument in the core constructor so the call to the core initializer method checks an uninitialized core member. Providing a default argument still doesn't fix the RuntimeError though.

2019-05-22 13:00 UTC, jngrad commented
I may have found a solution, let me check this on a clean source.

2019-05-22 13:50 UTC, fweik requested changes

2019-05-22 13:50 UTC, fweik commented on src/core/accumulators/Correlator.cpp
> +    fprintf(stderr, "args^2: %f %f %f\n", m_correlation_args[0],
This should probably be removed.

2019-05-22 13:53 UTC, jngrad commented on src/core/accumulators/Correlator.cpp
> +    fprintf(stderr, "args^2: %f %f %f\n", m_correlation_args[0],
Removed.

2019-05-22 13:53 UTC, fweik approved these changes

2019-05-22 14:36 UTC, jngrad commented
`coulomb_cloud_wall` is failing repeatedly

2019-05-22 18:08 UTC, KaiSzuttor commented
seems to be some UB?

2019-05-22 18:47 UTC, fweik commented
No, it's still `Illegal instruction`, so most likely some 64-bit code got in there

2019-05-22 18:57 UTC, KaiSzuttor commented
the printed error is not necessarily the actual if you google around...

> Am 22.05.2019 um 20:47 schrieb Florian Weik <notifications@github.com>:
> 
> No, it's still Illegal instruction, so most likely some 64-bit code got in there
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-05-22 18:59 UTC, KaiSzuttor commented
https://stackoverflow.com/questions/10354147/find-which-assembly-instruction-caused-an-illegal-instruction-error-without-debu

2019-05-24 16:59 UTC, jngrad commented
bors r=fweik

2019-05-24 18:00 UTC, merged