core: remove hip support.
espressomd/espresso pull request #2906
Opened 2019-06-13 10:56 UTC by KaiSzuttor

@RudolfWeeber

2019-06-13 11:03 UTC, fweik requested changes

2019-06-13 11:03 UTC, fweik commented on src/core/cuda_wrapper.hpp
> +#define SYMBOL(X) X
Please stick to the `DEVICE_` naming scheme.

2019-06-13 11:03 UTC, fweik commented on src/core/cuda_wrapper.hpp
> +#define LaunchKernel(kernel, blocks, threads, mem, stream, ...)          \
This should have an all uppper name to indicate that it is macro, maybe `DEVICE_LAUNCH`?

2019-06-18 16:32 UTC, RudolfWeeber commented
I have the impression that hip is not ready for use in ESpresso yet.
Looking at the issues and prs in the hip repository at github, things seem to be very much in flow.
I feel that with our limited resources we cannot commit to keeping hip support in Espresso working at all times. 

There are simply too many items to work on in Espresso propper for us to be dealing with bugs in tooling to that extent.

Support for AMD Gpus would be a very nice thing to have, but I think, for now we are stuck with Cuda.
We can continue to look at Hip in a features branch, such that we are not forced to keep it in sync with the development head at all times. Once the state of hip has converged a bit, we can and should retry.

A final decisoin will have to be made next week.

2019-06-28 11:10 UTC, fweik commented
We decided to defer this decision for 6 weeks.

2019-06-28 11:10 UTC, closed without merging