Installation instructions for Python 3
espressomd/espresso pull request #2916
Opened 2019-06-13 16:22 UTC by RudolfWeeber

This adds preliminary instructions to build with Python3. 
Once Python 2 support is removed, the docs have to be touched again, because they can then be simplified.

@jngrad 

 - [ ] Tests?
   - [ ] Interface
   - [ ] Core 
 - [ ] Docs?

2019-06-13 16:57 UTC, jngrad requested changes

2019-06-13 16:57 UTC, jngrad commented on doc/sphinx/installation.rst
> +.. code-block:: bash
```suggestion

.. code-block:: bash

```
I think there should always be a newline character both before and after a `code-block` directive.

2019-06-14 08:56 UTC, KaiSzuttor commented
@jngrad

2019-06-14 08:57 UTC, jngrad approved these changes

2019-06-14 09:36 UTC, KaiSzuttor commented
bors r+

2019-06-14 11:51 UTC, merged