WIP: LB mpi callback
espressomd/espresso pull request #2949
Opened 2019-06-27 10:13 UTC by KaiSzuttor

2019-06-27 11:11 UTC, KaiSzuttor commented
@fweik 

```
note: candidate template ignored: deduced
      conflicting types for parameter 'Args' (<const Utils::Vector<int, 3> &> vs. <Utils::Vector<int,
      3>>)
  auto call(Result::OneRank, boost::optional<R> (*fp)(Args...),
```

any idea?

2019-06-27 12:03 UTC, KaiSzuttor commented
the ```is_local``` check seems not to work properly... but I don't want to fiddle around with the unreadable lattice class.

2019-06-27 12:31 UTC, fweik commented
What do you mean? The condition is correct no?

2019-06-27 12:55 UTC, KaiSzuttor commented
the lb unit test hangs even when run on a single core, I assume because the ```is_local``` function returns false.

2019-06-27 13:00 UTC, fweik commented
This would cause an assertion failure in a debug build

2019-06-27 13:02 UTC, KaiSzuttor commented
really? which ```assert``` should trigger here?

2019-06-27 13:04 UTC, fweik commented
https://github.com/espressomd/espresso/blob/python/src/core/MpiCallbacks.hpp#L163

2019-06-27 13:14 UTC, KaiSzuttor commented
here it its:
```
Communication::MpiCallbacks::call(Communication::Result::OneRank, boost::optional<T> (*)(FArgs ...), Args ...) const [with R = double; FArgs = {const Utils::Vector<int, 3ul>&}; Args = {Utils::Vector<int, 3ul>}; std::remove_reference_t<T> = double]: Assertion `1 == boost::mpi::all_reduce(m_comm, static_cast<int>(!!local_result), std::plus<>())' failed
```
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/130841

2019-06-27 13:45 UTC, RudolfWeeber commented
:.,$d
@KaiSzuttor, the Walberla branch on my github repo might be of interest. As I understnad it, the parallelization scheme is the same for LBCPU and Walberla.

-- 
Dr. Rudolf Weeber
Institute for Computational Physics
Universität Stuttgart
Allmandring 3
70569 Stuttgart
Germany
Phone: +49(0)711/685-67717
Email: weeber@icp.uni-stuttgart.de
http://www.icp.uni-stuttgart.de/~icp/Rudolf_Weeber

2019-06-27 13:46 UTC, KaiSzuttor commented
@RudolfWeeber yes it is, but actually the issue seems to be my lack of willingness to understand the lattice class

2019-06-27 13:56 UTC, fweik commented
The problem is:
```
bool Lattice::is_local(const Vector3i&) const index 0 0 11 local_index_offset -1 -1 -1 grid 12 12 12
```
:-)

2019-06-27 14:55 UTC, KaiSzuttor commented
yes, my motivation got as far as printing those values aswell...

2019-06-27 14:56 UTC, fweik commented
Just check it by the position, that should work. (like `offset + index * agrid >= my_left` and so on). That matches the *style* of the rest of the class

2019-07-03 22:16 UTC, fweik requested changes
looks good except for some minor cosmetics

2019-07-03 22:16 UTC, fweik commented on src/core/grid_based_algorithms/lb_interface.cpp
> +void lb_set(Utils::Vector3i const &index, Kernel &&kernel) {
There is no need for the forwarding reference here, just say `Kernel kernel`

2019-07-03 22:16 UTC, fweik commented on src/core/grid_based_algorithms/lb_interface.cpp
> +auto lb_calc(Utils::Vector3i const &index, Kernel &&kernel) {
There is no need for the forwarding reference here, just say `Kernel kernel`

2019-07-03 22:16 UTC, fweik commented on src/core/grid_based_algorithms/lb_interface.cpp
> +auto lb_calc_fluid_kernel(Utils::Vector3i const &index, Kernel &&kernel) {
also no `&&`

2019-07-04 07:31 UTC, fweik approved these changes

2019-07-04 07:31 UTC, fweik commented
bors r+

2019-07-04 08:28 UTC, merged