Fix lbb
espressomd/espresso pull request #2987
Opened 2019-07-11 10:56 UTC by KaiSzuttor

Fixes #2983

2019-07-11 14:06 UTC, fweik requested changes

2019-07-11 14:06 UTC, fweik commented on src/core/grid_based_algorithms/lb_boundaries.cpp
> +Utils::Vector3d lbboundary_get_force(LBBoundary const *const lbb) {
On `const` less...

2019-07-11 14:14 UTC, KaiSzuttor commented on src/core/grid_based_algorithms/lb_boundaries.cpp
> +Utils::Vector3d lbboundary_get_force(LBBoundary const *const lbb) {
why?

2019-07-11 14:19 UTC, fweik commented
Passing by constant value makes no sense

On Thu, Jul 11, 2019, 16:14 Kai Szuttor <notifications@github.com> wrote:

> *@KaiSzuttor* commented on this pull request.
> ------------------------------
>
> In src/core/grid_based_algorithms/lb_boundaries.cpp
> <https://github.com/espressomd/espresso/pull/2987#discussion_r302566046>:
>
> > @@ -282,42 +282,32 @@ void lb_init_boundaries() {
>    }
>  }
>
> -// TODO dirty hack. please someone get rid of void*
> -int lbboundary_get_force(void *lbb, double *f) {
> +Utils::Vector3d lbboundary_get_force(LBBoundary const *const lbb) {
>
> why?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/pull/2987?email_source=notifications&email_token=AAG2FXYRUFPR5JD6AU4VUELP6454JA5CNFSM4IBAD6EKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB6FGDHA#discussion_r302566046>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAG2FX3ZQTIBIDT72PO57GDP6454JANCNFSM4IBAD6EA>
> .
>

2019-07-11 14:53 UTC, KaiSzuttor commented
what am I missing? I want the pointer and the pointed to object to be const

2019-07-11 15:04 UTC, fweik commented
You are passing the pointer by value. Passing by const value is not good.

On Thu, Jul 11, 2019, 16:53 Kai Szuttor <notifications@github.com> wrote:

> what am I missing? I want the pointer and the pointed to object to be const
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/espressomd/espresso/pull/2987?email_source=notifications&email_token=AAG2FX2YLWZIXUYNN62MY5DP65COVA5CNFSM4IBAD6EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZW6VPY#issuecomment-510519999>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAG2FXZ7GH46SXL7B535HCDP65COVANCNFSM4IBAD6EA>
> .
>

2019-07-11 15:14 UTC, KaiSzuttor commented
can you please give me ref.? I cannot see why this is not a good idea.

2019-07-11 15:23 UTC, jngrad commented
I'd also be interested in the reason. I'm currently refactoring the pressure/force/energy files and one minor part of the task consists in marking pointers as `const *const` whenever possible. This helps in functions creating pointers to bonded particles, where we don't want to accidentally re-assign a pointer passed as argument. I only know the rule that `const *const` should only appear in function implementations and `const*` in their declaration, to improve  readability and mask implementation details.

2019-07-12 08:37 UTC, KaiSzuttor commented
ping @fweik

2019-07-14 09:31 UTC, fweik commented
To me this is just line noise, but if you want to have it you can. The arguments that you have presented all seem to say the argument should be a reference and not a pointer...

2019-07-14 09:31 UTC, fweik approved these changes

2019-07-14 09:31 UTC, fweik commented
bors r+

2019-07-14 10:29 UTC, merged