Philox RNG for DPD
espressomd/espresso pull request #3009
Opened 2019-07-25 12:40 UTC by KonradBreitsprecher

Fixes the DPD part of #2683 

- Switched to Philox RNG
- Thermostat counter increment in common method in integrate.cpp

2019-07-25 12:55 UTC, fweik requested changes
LGTM except for minor cleanup

2019-07-25 12:55 UTC, fweik commented on src/core/nonbonded_interactions/nonbonded_interaction_data.hpp
> +#include "utils/Counter.hpp"
Why is this needed?

2019-07-25 12:55 UTC, fweik commented on src/core/dpd.hpp
> +extern std::unique_ptr<Utils::Counter<uint64_t>> dpd_rng_counter;
I think all of the philox and counter stuff can be moved to `dpd.cpp`, as far as I can tell it's not used elsewhere.

2019-07-25 13:53 UTC, fweik commented on src/core/dpd.hpp
> +extern std::unique_ptr<Utils::Counter<uint64_t>> dpd_rng_counter;
Why do you need to expose the counter?

2019-07-25 15:44 UTC, KonradBreitsprecher commented on src/core/dpd.hpp
> +extern std::unique_ptr<Utils::Counter<uint64_t>> dpd_rng_counter;
Right, thx..

2019-07-25 16:00 UTC, fweik approved these changes

2019-07-25 16:01 UTC, fweik commented
bors r+

2019-07-25 16:48 UTC, fweik commented
bors cancel

2019-07-26 08:47 UTC, jngrad commented
note: e26e92f is actually a merge

2019-07-26 08:49 UTC, KaiSzuttor commented
yeah, muscle memory...

2019-07-26 13:55 UTC, fweik commented
bros r+

2019-07-26 14:33 UTC, jngrad commented
bors r=fweik

2019-07-26 14:34 UTC, jngrad commented
bors r=fweik

2019-07-26 16:37 UTC, fweik commented
bors r+

2019-07-26 16:37 UTC, fweik commented
bors retry

2019-07-26 16:38 UTC, fweik commented
bors r-

2019-07-26 16:38 UTC, fweik commented
bors r+

2019-07-26 17:46 UTC, merged