Modernize Cell and ParticleList
espressomd/espresso pull request #3621
Opened 2020-04-01 21:51 UTC by fweik

Fixes #3539.

Depends on #3618.

Description of changes:
- More STL-like interface for `ParticleList`
- Replaced manual management by vector
- Avoid unneeded resizes of ghost cells during resort
- Made particles a member of `Cell` instead of a base

2020-04-02 18:05 UTC, jngrad requested changes
Overall LGTM

2020-04-02 18:05 UTC, jngrad commented on src/utils/include/utils/Bag.hpp
> +   * Efficiently swap to bags by swapping
```suggestion
   * Efficiently swap two bags by swapping
```

2020-04-02 18:05 UTC, jngrad commented on src/utils/include/utils/Bag.hpp
> + * The loser contract (compared to a vector) allows removing any
```suggestion
 * The looser contract (compared to a vector) allows removing any
```

2020-04-02 20:26 UTC, jngrad submitted a review, later dismissed
ok from my side

2020-04-03 09:48 UTC, RudolfWeeber commented
How do cells shrink again, once many particles have been in them and left.

2020-04-03 09:58 UTC, fweik commented
They don't, because there is no obvious place to do it. Do you think that is needed, and if so, why?

2020-04-03 12:51 UTC, KaiSzuttor submitted a review, later dismissed
LGTM

2020-04-03 17:49 UTC, fweik commented
@jngrad can you please approve again, I did a rebase. Maybe it is slightly annoying if the reviews are dismissed on change ^^

2020-04-03 17:55 UTC, jngrad approved these changes

2020-04-03 17:58 UTC, RudolfWeeber commented
I'm not sure about the never shrinking. 
Was that also the case for the old implementation?

Issues might arise for systems, where a really dense region migrates through space.
Say: A single polymer chain and a small number of much larger colloids. The colloid-colloid interaction would force a large cell size.

We probably have to try that out.

Otherwise, the PR looks good.

2020-04-03 18:26 UTC, fweik commented
The old implementation did shrink the cells. I think performance wise it's better to just not shrink it, that does not only avoid allocations, but also index updates for the whole cell. Memory is usually not
a limiting factor in MD simulations. Also I'd say if you have all of your particles in one cell, running out of memory is not your main problem :-) Let's see if this comes up, if so we can add an option to reclaim memory on resort or something.

2020-04-03 18:27 UTC, merged