WIP: Bond Refactor
espressomd/espresso pull request #3637
Opened 2020-04-07 11:54 UTC by fweik

Fixes #3084.

Description of changes:
- Proper data structure for bond lists
- Proper iterator for bonds
- Separate concerns between bond handling and bond parameters
- Replaced manual marshaling of bonds by serialization in ghost comm and mpiio
- Reorganization of bond kernels

2020-04-07 16:18 UTC, jngrad requested changes
That's a lot more readable, thanks! There are a few issues in the docs.

2020-04-07 16:18 UTC, jngrad commented on src/core/BondList.hpp
> + * a new one starts. This mechanism allows is to efficiently store
```suggestion
 * a new one starts. This mechanism allows us to efficiently store
```

2020-04-07 16:18 UTC, jngrad commented on src/core/BondList.hpp
> +   * @param pos Iterator iterator pointing to elementn to erase.
```suggestion
   * @param pos Iterator pointing to element to erase.
```

2020-04-07 16:18 UTC, jngrad commented on src/core/BondList.hpp
> +   * @return The numebr of bonds int the list.
```suggestion
   * @return The number of bonds in the list.
```

2020-04-07 16:18 UTC, jngrad commented on src/core/unit_tests/BondList_test.cpp
> +   * is empty. */
```suggestion
  /* BondList can be default constructed and a default constructed BondList
   * is empty. */
```

2020-04-07 16:18 UTC, jngrad commented on src/core/rattle.cpp
> +      /* Rigid bonds can not break */
```suggestion
      /* Rigid bonds cannot break */
```

2020-04-07 16:18 UTC, jngrad commented on src/core/BondList.hpp
> +   * @param bond to add.
```suggestion
   * @param bond Bond to add.
```

2020-04-07 16:18 UTC, jngrad commented on src/core/BondList.hpp
> + * @brief Check if the if a specific bond in a bond list.
```suggestion
 * @brief Check if there is a specific bond in a bond list.
```

2020-04-07 16:18 UTC, jngrad commented on src/core/BondList.hpp
> + * @return True iff the is a bond to the specified id of the specified type.
```suggestion
 * @return True iff there is a bond to the specified id of the specified type.
```

2020-04-07 20:30 UTC, jngrad submitted a review, later dismissed

2020-04-07 20:31 UTC, fweik commented
@jngrad when we bump the boost version, we should really grep for `BOOST_VERSION`

2020-04-07 20:41 UTC, jngrad commented
@fweik I've added the grep pattern in the open issue that tracks dependency version bumps in 4.2

2020-04-07 21:05 UTC, fweik commented
The issue picked up by the UB sanitizer is a bug in boost.container, that has since been fixed. Especially its fixed in version 1.66. Is there a schedule for bumping the boost version? Otherwise
I would just replace the boost vector by a stl vector, which would add 8 bytes per particle...

2020-04-07 21:19 UTC, jngrad commented
> Especially its fixed in version 1.66.

That's unfortunate, because Ubuntu 18.04 ships with `libboost-container1.65.1`, and `updates`/`backports` has nothing. Under these conditions, we'll most likely bump to 1.65. This can be done once `clang:6.0` is decommissioned (plan is in espressomd/docker#165).

2020-04-07 21:21 UTC, fweik commented
It's fixed from 1.58, so no problem. For the old versions we can just fall back to a stl vector.

2020-04-07 21:22 UTC, jngrad submitted a review, later dismissed

2020-04-07 21:45 UTC, fweik commented
To actually make the boost vector smaller, an even newer boost version is needed. I'll deal with this tomorrow together with the exclusions. This only affects the cache efficiency anyway...

2020-04-08 10:36 UTC, jngrad approved these changes

2020-04-08 12:28 UTC, merged