Modernize user guide
espressomd/espresso pull request #4504
Opened 2022-04-19 19:18 UTC by jngrad

Description of changes:
* use the *Alabaster* theme
   * visually light theme with consistent font sizes
   * natbib-style bibliography
* re-organize the user guide
   * collect information about running ESPResSo simulations into a self-contained chapter
   * move electrokinetics and reaction methods to self-contained chapters
   * make code examples more self-contained and remove pseudo-code
   * combine all BibTeX files into a single file
   * document running simulations in parallel with MPI
      * follow-up to mailing-list messages [Parallelization](https://lists.nongnu.org/archive/html/espressomd-users/2021-12/msg00011.html) and [max number of CPU's](https://lists.nongnu.org/archive/html/espressomd-users/2022-01/msg00001.html)

2022-04-20 01:03 UTC, pkreissl requested changes
In principle, your changes look good to me. For suggested changes see my comments.
Also, I did not build the doc yet, but I will do that later today to have a look at the visual and structure changes.

2022-04-20 01:03 UTC, pkreissl commented on doc/bibliography.bib
> +  number = {1-3},
This is also a number range, issues 1 to 3, so please use `1--3`.
The same goes for `crowl10a` (line 232)

2022-04-20 01:03 UTC, pkreissl commented on doc/sphinx/ek.rst
> +species. Note that this switching is only possible for the linkcentered
link-centered?

2022-04-20 01:03 UTC, pkreissl commented on doc/sphinx/ek.rst
> +The EKBoundary command allows one to set up (internal or external) boundaries for
``EKBoundary``?

2022-04-20 01:03 UTC, pkreissl commented on doc/sphinx/installation.rst
> +        For some algorithms like P\ :math:`^3`\ M, |es| needs the FFTW library
some algorithms [...] **need** (singular)

2022-04-20 01:03 UTC, pkreissl commented on doc/sphinx/integration.rst
> +The Stokesian Dynamics method allows to study the behaviour of spherical
I would go with AE "behavior" for consistency

2022-04-20 01:03 UTC, pkreissl commented on doc/sphinx/io.rst
> +* Pickling support of the :class:`espressomd.system.System` instance and
Obviously this is part of a item list. Still the meaning of this sentence is not immediately  clear to me (at least in the context of limitations) -- and grammatically there seems to be something missing.

2022-04-20 01:03 UTC, pkreissl commented on doc/sphinx/io.rst
> +  different environment than where it was loaded.
than where it was **written**. (or saved?)

2022-04-20 01:03 UTC, pkreissl commented on doc/sphinx/particles.rst
> +E.g., the following code adds a particle with rotation enabled around the x axis of its body frame::
x-axis (-- further down you use z-axis)

2022-04-20 01:16 UTC, jngrad commented
> Also, I did not build the doc yet, but I will do that later today to have a look at the visual and structure changes.

To build the docs, first run `rm -r build/doc/sphinx`, otherwise sphinx will complain that there are non-included .rst files: these are old files that have been removed in the source directory, but CMake doesn't clean them up. Also make sure you have the latest Sphinx and sphinx-contrib versions. Alternatively, you can download the [zip artifact](https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/314492/artifacts/download).

2022-04-20 01:17 UTC, jngrad commented on doc/sphinx/installation.rst
> +        For some algorithms like P\ :math:`^3`\ M, |es| needs the FFTW library
`|es|` expands to `ESPResSo`, which is singular

2022-04-20 08:36 UTC, pkreissl commented on doc/sphinx/installation.rst
> +        For some algorithms like P\ :math:`^3`\ M, |es| needs the FFTW library
Sure, my bad, somehow I completely overlooked the `|es| ...

2022-04-26 14:15 UTC, christophlohrmann approved these changes
Thanks for the big effort.
I am a big fan of reducing the advanced methods section

2022-04-26 15:34 UTC, pkreissl approved these changes
Thanks, lgtm!

2022-04-26 15:51 UTC, reinaual approved these changes

2022-04-26 15:51 UTC, reinaual commented on doc/sphinx/installation.rst
> +The resulting build with be quite slow but will enable many debugging tools.
typo

2022-04-26 15:53 UTC, jngrad commented on doc/sphinx/installation.rst
> +The resulting build with be quite slow but will enable many debugging tools.
good catch, I'll wrap this up when running the spellchecker during the release process next month

2022-04-26 16:28 UTC, merged