Add tutorial on Widom particle insertion
espressomd/espresso pull request #4546
Opened 2022-08-01 14:44 UTC by davidbbeyer

Description of changes:
- Adds a tutorial that teaches users how to use the Widom particle insertion method to determine the excess chemical potential of a system. The considered system consists of a monovalent salt solution. Could potentially be used in the tutorials for the summer school, as discussed last Tuesday.

2022-08-03 08:39 UTC, davidbbeyer commented
Maybe @kosovan or @pm-blanco could review it?

2022-08-23 13:42 UTC, mebrito requested changes
Here, there are some suggestions for changes. The most import would be to state clearly in the introduction what the method does and what will be done throughout the tutorial.

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "However, no valuable information of the system's dynamics can be obtained.\n",
```suggestion
    "However, no valuable information of the system dynamics can be obtained.\n",
```

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "Because the investigated system is a monovalent salt the concentrations (and thus, densities) of positive and negative ions are the same.\n",
```suggestion
    "Since the investigated system is a monovalent salt, the concentrations (and thus, densities) of positive and negative ions are the same.\n",
```

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "\n",
Up to this point it isn't fully clear the idea of the method. It would be nice to clearly state it. For example: "The integral in Eq. (4) suggests a method to compute ... ". Furthermore, I would say in a few words how it is done in ESPResSo: is the integral done by  MC/Langevin dynamics combination?

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "The system under consideration here consists of $N$ monovalent ion pairs in an implicit solvent with $\\epsilon_\\text{r} = 78$, which is a simple model (``restricted primitive model'') for an a
From this line on, I would shift to a different section, where I would explain what we are going to simulate, what we are going to measure and against what we compare in order to test the method. The section could be titled "Simulation of aqueous salt solution" or "Excess chemical potential of a salt solution".

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "PREF = 1/(10**3 * avo * sigma**3) # Prefactor to mol/L\n",
`sigma`, `avo` and `PREF` could be moved down in the notebook where they are going to be used, in order to avoid confusion about the simulation units.

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "system = espressomd.System(box_l=3 * [10.0])\n",
```suggestion
    "box_l_init = 10.0\n",
    "system = espressomd.System(box_l=3 * [box_l_init])\n",
```

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "system.part.add(type=[types[\"Xplus\"]]*N_ION_PAIRS, pos=np.random.rand(N_ION_PAIRS, 3) * 20.0, q = [charges[\"Xplus\"]]*N_ION_PAIRS)\n",
```suggestion
    "system.part.add(type=[types[\"Xplus\"]]*N_ION_PAIRS, pos=np.random.rand(N_ION_PAIRS, 3) * box_l_init, q = [charges[\"Xplus\"]]*N_ION_PAIRS)\n",
```

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "system.part.add(type=[types[\"Xminus\"]]*N_ION_PAIRS, pos=np.random.rand(N_ION_PAIRS, 3) * 20.0, q = [charges[\"Xminus\"]]*N_ION_PAIRS)\n",
```suggestion
    "system.part.add(type=[types[\"Xminus\"]]*N_ION_PAIRS, pos=np.random.rand(N_ION_PAIRS, 3) * box_l_init, q = [charges[\"Xminus\"]]*N_ION_PAIRS)\n",
```

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "* Implement a function ``warmup `` that removes potential overlaps between particles\n",
```suggestion
    "* Implement a function ``warmup `` that removes potential overlaps between particles and performs a warmup integration\n",
```

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "* After the overlaps have been removed, the integrator should be switched to Velocity-Verlet (with Langevin thermostat) in order to perform a warmup integration"
```suggestion
    "* Notice that, after the overlaps have been removed, the integrator should be switched to Velocity-Verlet (with Langevin thermostat) in order to perform a warmup integration"
```

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "* Refer to the documentation to find out how to set up Widom particle insertion ([Widom Insertion](https://https://espressomd.github.io/doc/reaction_methods.html#widom-insertion-for-homogeneous-
Link to documentation doesn't work

2022-08-23 13:42 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "which results from an empirical extension of the Debye-Hückel theory.\n",
Add references for mu_ex^DH and mu_ex^Davies

2022-09-23 08:27 UTC, davidbbeyer commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "PREF = 1/(10**3 * avo * sigma**3) # Prefactor to mol/L\n",
I think this part should be left as it is for the following reason: in the exercise that follows directly below, one has to setup the system and thus set the box size and time step. This task thus already requires a notion of units.

2022-09-23 08:30 UTC, davidbbeyer commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "system = espressomd.System(box_l=3 * [10.0])\n",
I fixed that.

2022-09-23 08:30 UTC, davidbbeyer commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "system.part.add(type=[types[\"Xplus\"]]*N_ION_PAIRS, pos=np.random.rand(N_ION_PAIRS, 3) * 20.0, q = [charges[\"Xplus\"]]*N_ION_PAIRS)\n",
I fixed that.

2022-09-23 08:30 UTC, davidbbeyer commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "* Refer to the documentation to find out how to set up Widom particle insertion ([Widom Insertion](https://https://espressomd.github.io/doc/reaction_methods.html#widom-insertion-for-homogeneous-
I fixed it.

2022-09-23 08:34 UTC, davidbbeyer commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "which results from an empirical extension of the Debye-Hückel theory.\n",
I added a reference.

2022-09-28 13:55 UTC, mebrito requested changes
Request for small wording changes in the text.

2022-09-28 13:55 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "In a pure MD simulation, there is no direct way to access the chemical potential, since it is related to changes in the particle number, which is fixed in an MD simulation.\n",
```suggestion
    "In a pure MD simulation, there is no direct way to access the chemical potential, since it is related to changes in the particle number that is typically fixed.\n",
```

2022-09-28 13:55 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "It corresponds to the difference in the Helmholtz free energy $F$ or Gibbs free energy $G$ for bringing a particle from infinity into the system, or equally for removing one particle, thus chang
```suggestion
    "and corresponds to the difference in the Helmholtz free energy $F$ or Gibbs free energy $G$ when adding or removing one particle in the system.\n",
```

2022-09-28 13:55 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "  \\mu_{\\alpha} = \\left(\\frac{\\partial G}{\\partial N_\\alpha} \\right)_{p,T,N_{\\beta\\neq\\alpha}} = \\left(\\frac{\\partial F}{\\partial N_\\alpha}\\right)_{V,T,N_{\\beta\\neq\\alpha}} \\
```suggestion
    "  \\mu_{\\alpha} = \\left(\\frac{\\partial G}{\\partial N_\\alpha} \\right)_{p,T,N_{\\beta\\neq\\alpha}} = \\left(\\frac{\\partial F}{\\partial N_\\alpha}\\right)_{V,T,N_{\\beta\\neq\\alpha}} \\quad ,\\tag{1}\n",
```

2022-09-28 13:55 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "In the above expression, $\\Delta U$ is the energy difference of the system before and after the insertion of an additional particle (\"test particle\") into the system.\n",
```suggestion
    "In the above expression, $\\Delta U$ is the energy difference of the system before and after the insertion of an additional particle (\"test particle\") into the system, and $\\langle...\\rangle$ is the canonical average for a system with $N$ particles.\n",
```

2022-09-28 13:55 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "The method of Widom insertion introduced can be used to calculate the excess chemical potential for this system.\n",
```suggestion
    "The introduced method of Widom insertion can be used to calculate the excess chemical potential for this system.\n",
```

2022-09-28 13:55 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "<a id='[2]'></a>[2] P. Atkins, J. de Paula and J. Keeler. Physical Chemistry. Oxford University Press, 2018."
```suggestion
   "<a id='[1]'></a>[1] B. Widom. Some topics in the theory of fluids. Journal of Chemical Physics, 39:2808, 1963.  \n",
    "<a id='[2]'></a>[2] P. Atkins, J. de Paula and J. Keeler. Physical Chemistry. Oxford University Press, 2018."
```

2022-09-28 13:55 UTC, mebrito commented on doc/tutorials/widom_insertion/widom_insertion.ipynb
> +    "In order to sample the canonical average $\\langle...\\rangle$, one has to insert a test particle into many different configurations of the system (sampled according to the canonical distributio
```suggestion
       "The expression thus suggests that the excess chemical potential can be computed using the following procedure.\n",
    "The canonical average $\\langle\\exp(-\\beta\\Delta U)\\rangle$ can be computed by inserting a test particle into many different configurations of the system (sampled according to the canonical distribution) and then averaging the associated Boltzmann factor $\\exp(-\\beta\\Delta U)$.\n",
```

2022-09-28 15:41 UTC, mebrito submitted a review, later dismissed

2022-09-30 16:42 UTC, jngrad approved these changes, later dismissed

2022-09-30 18:42 UTC, jngrad submitted a review, later dismissed

2022-09-30 20:20 UTC, jngrad approved these changes

2022-09-30 20:43 UTC, merged