Add tutorial on GCMC
espressomd/espresso pull request #4670
Opened 2023-02-13 19:21 UTC by lburth

Fixes #4575 

Description of changes:
- Adds a tutorial, that teaches users how to simulate systems in the Grand-Canonical ensemble with the Grand-Canonical Monte Carlo.

2023-08-08 08:58 UTC, christophlohrmann requested changes
This is a very well written tutorial. I have a bunch of minor comments, the only thing major is that after the last plot, the physics should be discussed in more detail to interpret the main result.
Otherwise: Thanks a lot, well done

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "In the grand canonical ensemble, the volume $V$, the temperature $T$ and the chemical potentials $\\mu_i$ of the exchangeable species $i$ rather than the particle numbers $N_i$ are fixed.The che
missing space in last sentence

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "p^\\mathrm{G}\\left(\\left\\{N_i\\right\\},\\xi\\right) = \\frac{\\exp\\left(-\\beta \\left(H(\\xi)-\\sum_{i=1}^{N_\\mathrm{s}}\\mu_iN_i\\right)\\right)}{Z^\\mathrm{G}h^{3N}\\prod_{i=1}^{N_\\mat
define N_s

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "Z^\\mathrm{G}\\left(\\left\\{\\mu_i\\right\\},V,T\\right) = \\sum_{N_1=0}^{\\infty}...\\sum_{N_\\mathrm{s}=0}^{\\infty}Z\\left(\\left\\{N_i\\right\\},V,T\\right)\\exp\\left(\\beta \\sum_{i=1}^{N
define Z

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "In the case where one requires electroneutrality of the phases, due to the additional constraint, the electrochemical potential $\\overline{\\mu}_i=\\mu_i+z_ie\\psi$ rather than the chemical pot
define z, e, psi

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "It is easy to see that the acceptance probability \n",
avoid such phrases to not discourage beginners

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "In the GCMC method the insertion and deletion moves are implemented in the following fashion. First of all it is determined randomly with equal probability if an insertion or deletion move is pe
missing "the" in last sentence

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "\\mu_i = \\left(\\frac{\\partial F}{\\partial N_i}\\right)_{T, V, \\left\\{N_j\\right\\}_{j\\neq i}}.\n",
define F

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "This simplification is valid if we are only interested in observables which do not depend on the momenta."
it's not really a simplification (in the sense of an approximation).

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "This effect is called the Donnan effect <a href='#[3]'>[3]</a> and leads to an unequal partioning of salt between the reservoir and the system. The partitioning can be quantified using the parti
define c

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "    \\begin{array}{ll}\n",
why do we have two different definitions?

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "one can obtain the following solution for an ideal system:\n",
define ideal

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "     \\xi^{\\text{Donnan}} = -\\frac{c_{\\text{M}^-}^{\\text{sys}}}{2c_{\\text{X}^+,\\text{X}^-}^{\\text{res}}} + \\sqrt{\\left(\\frac{c_{\\text{M}^-}^{\\text{sys}}}{2c_{\\text{X}^+,\\text{X}^-}
maybe a plot would be nice if it's not too much work

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "from espressomd.interactions import *\n",
avoid star-imports

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "sigma = 3.55e-10 # Sigma in SI units\n",
where does this specific sigma come from?

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "pref = 1/(10**3 * avo * sigma**3) # Prefactor to mol/L\n",
could we use the pint package here instead of manual unit conversions?

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "## Setup of the simulation\n",
basically same header as previous section

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "LJ_SIGMA = 1.0\n",
how do these parameters relate to the SI-parameters introduced above?

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "fene = FeneBond(k=30, d_r_max=1.5, r_0=0.0)\n",
why is the bond length 0?

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "N_plus = n_salt + N_CHAINS*N_MONOMERS_PER_CHAIN\n",
mention electroneutrality constraint and where the counterions come from

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "        system.non_bonded_inter[types[i], types[j]].lennard_jones.set_params(epsilon=LJ_EPSILON, sigma=LJ_SIGMA, cutoff=LJ_SIGMA * 2**(1.0/6.0), shift=\"auto\")\n",
you could use the built-in WCA interaction

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "RE.set_non_interacting_type(type = len(types)+1)\n",
what does this line do?

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +      "100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00,
remove output from tutorial before commiting/pushing

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "        system.integrator.run(1000)\n",
maybe give these numbers as predefined variables

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "* Plot the universal partition coeffiecients obtained by measuring the partition coefficient $\\xi_-$ and $\\xi_+$ in the simulation against $c_{\\mathrm{M}^-}/(2c_{\\mathrm{salt}}^{\\mathrm{res
not sure plotting is a meaningful exercise

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "* Interpret the deviation of the simulation results from the ideal prediction."
there should definitely be a solution to this question

2023-08-08 08:58 UTC, christophlohrmann commented on doc/tutorials/grand_canonical_monte_carlo/grand_canonical_monte_carlo.ipynb
> +    "Here we want to investigate a polyelectrolyte solution that is coupled to a reservoir containing a monovalent salt, as shown schematically in figure 1. The small salt ions (X$^+$ and X$^-$) can
maybe add a sentence on the relevance/usefulness of this system

2023-08-28 08:30 UTC, lburth commented
Thank you for your review and your annotations. I have now worked in your annotations and added an interpretation of the final plot. In addition I have changed the sample sizes a bit to speed up the runtimes.

2023-09-27 13:58 UTC, christophlohrmann commented
Looks really nice now, thanks for the work you put in.
For me, the solutions to the exercises are shown when I open the notebook. Please check if it looks the same for you and make the default not-shown if needed.
Otherwise this can be merged

2023-09-27 17:16 UTC, lburth commented
> Looks really nice now, thanks for the work you put in. For me, the solutions to the exercises are shown when I open the notebook. Please check if it looks the same for you and make the default not-shown if needed. Otherwise this can be merged
Thanks for the review. Now the default is that the solutions are hidden.

2023-09-28 07:53 UTC, christophlohrmann approved these changes

2023-11-07 11:53 UTC, jngrad approved these changes

2023-11-07 11:53 UTC, merged