Electrokinetics tutorial
espressomd/espresso pull request #4782
Opened 2023-09-04 13:45 UTC by reinaual

2023-09-06 14:06 UTC, christophlohrmann requested changes
The physics in the tutorial semms good, especially the reaction in turbulent flow looks fantastic. Obviously, the exercises are still missing.
The language/style of the descriptive text needs to be improved, but that's something I could do

2023-09-06 14:06 UTC, christophlohrmann commented on doc/tutorials/electrokinetics/electrokinetics.ipynb
> +    "species[BOX_L[0] // 2, BOX_L[1] // 2, 0].density = 1.0"
I would put 1/agrid**3 here to make sure there is one unit of material in the system.
Alternatively would using a gaussian as the starting condition reduce numerical errors connected to discretised gradients?

2023-09-06 14:06 UTC, christophlohrmann commented on doc/tutorials/electrokinetics/electrokinetics.ipynb
> +    "total_frames = 200\n",
the video takes way too long to be produced. While the simulation is running, students can't use their interactive session to do subsequent tasks. Could the order be switched so this is last? It also seems like the most advanced system.

2023-09-06 14:06 UTC, christophlohrmann commented on doc/tutorials/electrokinetics/electrokinetics.ipynb
> +    "animation.FuncAnimation(fig, draw_frame, frames=range(total_frames), interval=300)"
would be cool if the boundaries were visible in the video

2023-09-14 12:49 UTC, christophlohrmann reviewed
Exercises are a bit short (especially in the summer school context where we need people to do stuff for 90mins) but cover the essentials.
Text still needs some polishing. I could take it from here

2023-09-20 11:47 UTC, christophlohrmann commented
@jngrad @reinaual ready for review

2023-09-27 13:29 UTC, christophlohrmann approved these changes
can I approve my own changes?

2023-10-02 14:29 UTC, jngrad approved these changes

2023-10-02 14:45 UTC, merged