Support recent CMake and NumPy versions
espressomd/espresso pull request #4992
Opened 2024-09-11 17:46 UTC by jngrad

Description of changes:
- add experimental support for NumPy 2
- modernize CMake build system

2024-09-11 19:06 UTC, jngrad commented
This PR was backported to ESPResSo 4.2.2 in openSUSE:Factory via [request 1200178](https://build.opensuse.org/request/show/1200178) to fix the failing x86_64 builds.

2024-09-12 07:45 UTC, reinaual requested changes

2024-09-12 07:45 UTC, reinaual commented on CMakeLists.txt
> +  GIT_TAG        862a7537a366f0c32f0c25e46bd107bea590faea)
```suggestion
  GIT_TAG        862a7537a366f0c32f0c25e46bd107bea590faea
)
```

2024-09-12 08:37 UTC, reinaual approved these changes

2024-09-12 08:38 UTC, merged