bond breakage
espressomd/espresso pull request #4995
Opened 2024-09-25 18:16 UTC by 1234somesh

Fixes #

Description of changes:
-

2025-02-07 12:59 UTC, RudolfWeeber approved these changes, later dismissed

2025-02-11 15:14 UTC, jngrad requested changes
The feature is missing a test. The feature throws an exception.

2025-02-11 15:14 UTC, jngrad commented on src/python/espressomd/bond_breakage.py
> +    _so_bind_methods = ("execute",)
@RudolfWeeber I'm not a big fan of having this feature as a stand-alone class. It currently only works on the main `System` instance, and ignores all other instances. How about making this feature a member method of the `BreakageSpecs` class? Then one could do `system1.bond_breakage.execute()` to execute all specs.

2025-02-18 12:11 UTC, RudolfWeeber commented
The probelm was that
* bond breakage handlers return true if they did something
* but kernels to cell_strucutre::bonded_loop (and short_range_loop) return true if a bond is broken


I.e. the return value of the former has to be discarded in the latter.

2025-02-18 12:54 UTC, RudolfWeeber commented on src/python/espressomd/bond_breakage.py
> +    _so_bind_methods = ("execute",)
moved it.

2025-02-19 13:10 UTC, jngrad approved these changes

2025-02-19 13:30 UTC, merged